### ISSUE TITLE
[FEATURE] import this

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-lego#106]
We're bound to learn lessons that can be combined into a "Zen of Scikit-Lego". Just like projects like sympy and evol we might want to add our own. If there are general zen lessons learned while making this tool: let's up 'em here. Some day in the future somebody might gain enlightenment by typing. 

```
from sklego import this
```

**Comment by koaning** [comment]
if you don't know the requirements you don't know if they're met, 
if you haven't gotten to where you're going, you aren't there yet.

**Comment by koaning** [comment]
you cannot understand a problem by avoiding it, 
but sometimes the problems go away if you ignore them.

**Comment by koaning** [comment]
you can add lot's of features and consider every extension,
but the path towards ruin is paved with good intensions.

**Comment by arthurpaulino** [comment]
[the unknown may be ignored,
but infinity is ever present.](https://github.com/koaning/scikit-lego/pull/119#discussion_r278881928)

**Comment by koaning** [comment]
> defer responsibility to the end user
> this might just empower them

**Comment by koaning** [comment]
https://github.com/koaning/scikit-lego/pull/153

> Off by one errors are hard to catch,
> Flipping the sign can be even harder (and worse).

**Comment by koaning** [comment]
First version of this: https://github.com/koaning/scikit-lego/pull/239.

**Comment by Menziess** [comment]
Correlation does not imply causation.

**Comment by koaning** [comment]
There's a PR here which will add it to the docs. https://github.com/koaning/scikit-lego/pull/409

I might also say that the poem feels complete. People can still add to it. But no longer needed to have this issue list.
