### ISSUE TITLE
[BUG] Problems with make docs

### ISSUE THREAD

**Issue by arthurpaulino** [koaning/scikit-lego#127]
Calling `$ make docs` executes:

```bash
$ sphinx-apidoc -f -o doc/api sklego
$ sphinx-build doc docs
```

But `sphinx-apidoc` is undoing what has been done [here](https://github.com/koaning/scikit-lego/pull/125#issue-274203155):

> 1. Removed internal/empty modules from docs page

I think it's possible to have more control over what `sphinx-apidoc` does, but I'm not really sure. I've tried messing with an `__all__` variable (list) in `sklego/__init__.py` but I had no success.

**Comment by koaning** [comment]
yeah this was on my mental todo list. good to have on an actual issue list :)

**Comment by arthurpaulino** [comment]
I do think it has something to do with the `__all__` variable though, as if we would allow sphinx to document what each module exports, only...

**Comment by koaning** [comment]
We are considering replacing some of the .rst documents here with jupyter notebooks. This allows us to more easily test the documentation via `nbval` and (let's be honest) markdown is easier learned than rst.

**Comment by arthurpaulino** [comment]
It looks great. Can it generate modules/classes docs automatically? It's new to me.

**Comment by koaning** [comment]
Ah no. But I think there's two parts we want to for the documentation. 

1. There's the detail guide. The part of the docs that shows you all the settings that are possible. 
2. But perhaps more importantly there's the "how do I use it" part. This would the an example that demonstrates how that it is being used and is more of a "getting started" bit. 

It is **the second part** bit that I'd want to do with jupyter notebooks. The first part would still occur via normal sphinx.

**Comment by koaning** [comment]
I believe this is now fixed. Will open again if need be.
