### ISSUE TITLE
[DOCS] broken github url

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-lego#136]
The URL to github seems broken. 

![image](https://user-images.githubusercontent.com/1019791/57760010-23bd7b00-76fb-11e9-99c6-8ecb7a55b862.png)

**Comment by koaning** [comment]
![image](https://user-images.githubusercontent.com/1019791/57760044-36d04b00-76fb-11e9-8e91-38e0fb948be3.png)

**Comment by MBrouns** [comment]
Seems fixed
