### ISSUE TITLE
[DOCS] jupyter sphinx

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-lego#145]
https://blog.jupyter.org/integrating-output-in-documentation-with-jupyter-sphinx-ecf569ddab85

**Comment by koaning** [comment]
Extra benefit. This would allow us to unit test the notebooks via `nbval` and this would make it a lot nicer to write great documentation!

**Comment by akhmerov** [comment]
As of today, you can also turn thebelab (live code execution) with minimal extra config.

**Comment by koaning** [comment]
Docs work now. The "thebelab" sounds like a neat idea, but I prefer to not introduce anything new to the docs for now. Writing more proper content might be a better idea.

**Comment by akhmerov** [comment]
BTW, you're using `nbsphinx` (https://github.com/spatialaudio/nbsphinx) which includes .ipynb in docs, not `jupyter-sphinx` (http://github.com/jupyter/jupyter-sphinx/) which evaluates code from .rst and includes the output.
