### ISSUE TITLE
[FEATURE] WordList Feature Maker

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-lego#149]
During class last Friday we wanted to make a simple benchmark. Not just use `CountVectorizer` but build a simple transformer that just selects positive/negative words. 

We ended up with something like;

```python
class WordyTransformer(BaseEstimator, TransformerMixin):
    def __init__(self):
        self.good_words = ['gemakkelijk', 'fijn', 'handig', 'super', 'veel',
                           'snel', 'heel', 'gemak', 'goed', 'service', 'makkelijk']
        self.bad_words = ['minder', 'terug', 'erg', 'vind', 'leverbaar',
                          'keer', 'voorraad', 'steeds', 'slecht']

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        goods = [sum([w in s for w in self.good_words]) for s in X]
        bads = [sum([w in s for w in self.bad_words]) for s in X]
        return np.array([goods, bads]).T
```

We could build something similar, that you can give a list of lists of words and that we will . simply count how often these words appear. For benchmarking this might not be a bad idea.

**Comment by koaning** [comment]
@MBrouns thoughts?

**Comment by MBrouns** [comment]
I think it can be nice to have something like this but how does this compare to using a `CountVectorizer` and then only selecting the columns of the good and bad words?

**Comment by koaning** [comment]
yeah. it feels allmost too basic to add to this library. will close issue.
