### ISSUE TITLE
[BUG] p-percent divide by zero warnings.

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-lego#163]
There's a lot of warnings when I use the p-percent score in a grid search with the fair classifier. 

![image](https://user-images.githubusercontent.com/1019791/61027244-f79a3f80-a3b5-11e9-87c9-d97a1d8ab428.png)

I think the warning is good, but seeing a kilometer of red that you gotta scroll through in a notebook is less ideal and might frighten people who are new. Can we maybe apply some smoothing to prevent this error?

**Comment by kayhoogland** [comment]
https://github.com/koaning/scikit-lego/pull/185#pullrequestreview-280886896

**Comment by MBrouns** [comment]
fixed in #195
