### ISSUE TITLE
feature request: only apply random noise in `RandomAdder` to training data

### ISSUE THREAD

**Issue by MBrouns** [koaning/scikit-lego#17]
Currently, `RandomAdder` adds noise to data both at training and at prediction time. This causes predictions to become non-deterministic and it offers no clear benefit in most cases I can think of. 

I suggest changing the default behaviour of the transformer to only add random noise to the train data and optionally through a constructor flag also to the prediction data.

**Comment by koaning** [comment]
I think we agree this can't be done. Close issue?

**Comment by MBrouns** [comment]
So I got asked a similar type of thing in todays training where someone wanted to drop rows with too many missing values from train but not from test so I was toying around to see if I could find something that would work. 

I might have figured out a way but I'm not sure I like it all that much:

```
import pandas as pd
import hashlib

class TrainOnlyMixin(BaseEstimator, TransformerMixin):
    
    def fit(self, X, y):
        self.df_hash_ = self.hash_df(X)
        return self
    
    
    @staticmethod
    def hash_df(df):
        return hashlib.sha256(pd.util.hash_pandas_object(df, index=True).values).hexdigest()
    
    def transform(self, X, y=None):
    
        if self.hash_df(X) == self.df_hash_:
            return self.transform_train(X)
        
        else:
            return self.transform_test(X)
```

I basically store a hash of the train dataframe and compare `X` with it in `transform` and then call `transform_train` or `transform_test`. I think this can be made quite generic and I can't think of a case where it wouldn't work. What do you think?

**Comment by koaning** [comment]
My first thought: **WE NEED TO BE CAREFUL** there's methods that might do a partial fit and then this would totally break.

My second thought: this could work though.

**Comment by MBrouns** [comment]
1. Pipelines don't implement `partial_fit` so that shouldn't be a problem i think

2. 😄 

3. So far I've come up with the following use cases:
    a. dropping rows with many missing values from train but not from test 
    b. adding noise to train but not to test
    c. removing outliers from training data
    
4. As is no, but it is possible to calculate a hash on a numpy array afaik

5. Agreed, probably have this as a mixin where `transform_test` has a default implementation to return `X`

**Comment by MBrouns** [comment]
#81
