### ISSUE TITLE
[FEATURE] adding a prior ... it might be a good meta

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-lego#201]
Sometimes it makes sense to add a prior to your classifier. If you know that your dataset is unbalanced for example.

**Comment by koaning** [comment]
1. I think `ClassifierPrior` might be slightly better as a name but I am open to suggestions. 
2. This sounds good.
3/4. Why would you need to store/use the confusion matrix? 

This sounds a lot like the [confusion balancer](https://scikit-lego.readthedocs.io/en/latest/meta.html#Confusion-Balancer) that I was working on Friday. The impression I got from your idea is that you don't check the confusion matrix but instead use the `prior` parameter that is passed apon initialising the `ClassifierPrior`. This is a very valid idea when your train data is expected to not represent reality. 

Was this not the original idea or did I misunderstand the idea?

**Comment by jsamoocha** [comment]
About the confusion matrix: assume a binary classifier that predicts _Y_ (having classes _a_ and _b_). Say the inner classifier predicts _Y_hat_ = _a_. If we're interested in P(Y=a|Y_hat=a), applying Bayes rule, we need to know P(Y_hat=a|Y=a) (i.e. the True Positive Rate if "a" is the "positive" prediction) and P(Y_hat=a) (i.e. all "a" predictions / all predictions). Don't you need the confusion matrix to compute that likelihood and marginal?

**Comment by koaning** [comment]
It is a shame that github does not render mathjax, but here goes. 

![image](https://user-images.githubusercontent.com/1019791/65637976-78e09600-dfe5-11e9-8f5e-3f2c1442804b.png)

This does make a bit of sense actually. I originally thinking you just wanted to reweigh the classes by saying one of them is more likely. You don't need a confusion matrix for that. Would also be a nice feature.

**Comment by jsamoocha** [comment]
Ok, let me do both options, then. This means the classifier gets an additional param `evidence` that can have values `predict_proba`, `confusion_matrix`, or `both`.

In case of `predict_proba`, the prediction result will be a balance(*) between the inner estimator's `predict_proba()` result and the prior probabilities.

In case of `confusion_matrix`, the result will use the inner estimator's `predict()`, confusion matrix and Bayes Rule as described above.

In case of `both`, we'll need to find a probabilistically sound balance between the 2 approaches (WIP).

(*) As for balance, an additional parameter `alpha` could be added, similar to your approach in the confusion balancer?

For the class name, how about `SubjectiveClassifier`?

**Comment by jsamoocha** [comment]
Just started with the easiest part, based on the confusion matrix. See #213 (WIP) for a sneak preview.

**Comment by koaning** [comment]
Closing this issue for now. Detailed discussions are better served in a new thread.

**Comment by DavidRosen** [comment]
sklego.meta.SubjectiveClassifier is not working as I expected -- can it do what I want?  Forgive me if I don't use the correct terminology or if this is not the right place to ask this.

I have a three-class classifier whose training set has certain non-uniform class prevalences (frequencies) train_prevalence (which has three elements).

What I *want* to get is a classifier whose predictions will be the same *as if* I had instead trained my classifier with class_weight='balanced' (which I didn't), in other words effectively with uniform class prevalences in the training set.

I had *thought* that if I used SubjectiveClassifier(orig_model, prior=uniform_prediction_prior) I would get this, but instead I get a model identical to my orig_model when using this uniform prior.

Note that uniform_prediction_prior has value {0: 0.3333333333333333, 1: 0.3333333333333333, 2: 0.3333333333333333}.

Is there a way to get what I'm looking for?

I noticed that I get  *almost* what I'm looking for if I give the least weight to my most prevalent classes by setting (with train_prevalence being a pd.Series):
```
prior = 1.0/train_prevalence
prior /= prior.sum() # normalize
prior = {c:prior[c] for c in prior.index}
model = SubjectiveClassifier(orig_model, prior=prediction_prior, evidence='predict_proba') 
```
But the result only approximates the result I would get if I had trained the original classifier with class_weight='balanced'.

**Comment by jsamoocha** [comment]
`SubjectiveClassifier` does not intend to correct for class imbalances in your training set. Instead, it modifies predictions to reflect (subjective, perceived) class distributions in the real world. This is why you're getting identical results to the original model when using a uniform prior.

There are many methods to handle training set class imbalance, but this is not one of them.

**Comment by DavidRosen** [comment]
Right, so if my real-world class distribution is uniform, but my training data is imbalanced, how do I modify the predictions of my classifier to reflect the uniform real-world distribution instead of the imbalanced training prevalences?   I thought SubjectiveClassifier could do this.

**Comment by jsamoocha** [comment]
I'm not sure I understand what you're trying to achieve.

>What I want to get is a classifier whose predictions will be the same as if I had instead trained my classifier with class_weight='balanced' (which I didn't), ...

If you want this, why didn't you train an (e.g.) `LogisticRegression` classifier with balanced class weights?

Do you want to correct for class imbalance in your training set, _at training time_, or do you like to correct your predictions _at runtime_ based on last-minute subjective prior "data" that is not a feature of your model?

**Comment by DavidRosen** [comment]
I want to correct the predictions at runtime, not at training time.  I would like to be able to set any desired prior at runtime (without re-training the model itself), starting with, but not limited to, a uniform prior.

**Comment by jsamoocha** [comment]
Just checking if I understand correctly, would you like to do something as:

```python
estimator = SubjectiveClassifier(MyInnerEstimator(), prior={'a': 0.2, 'b': 0.8}).fit(X, y)
# after some time, having new data to make predictions
estimator.prior = {'a': 0.5, 'b': 0.5}
estimator.predict(new_x)
# after more time and newer data
estimator.prior = {'a': 0.9 'b': 0.1}
estimator.predict(newer_x)
```

If so, I think I see how that can be fixed. To better understand what you expect as posterior probabilities, you could help by giving a toy example of prior(s), confusion matrix of the inner estimator, and expected posteriors (see e.g. the parameterization of [test_posterior_computation()](https://github.com/koaning/scikit-lego/blob/6127619a942823237e3200887164e6b3fb354e2b/tests/test_meta/test_subjective_classifier.py#L75)). [This article](https://lucdemortier.github.io/articles/16/PerformanceMetrics) may also be helpful as background info.

@koaning In case of a (relatively small, backward compatible) fix, do you want a new issue to discuss/track that, or can I just create a PR?

**Comment by DavidRosen** [comment]
Yes, but for starters, how can I adjust the inner classifier to make predictions for a uniform prior?  When I use {1: 0.5, 2: 0.5} it has no effect and simply returns a classifier that makes the same predictions as the inner classifier did, which implicitly reflects the original prior distribution from the training set, which is *not* uniform at all.

**Comment by jsamoocha** [comment]
Please correct me if I'm wrong, but isn't a uniform prior equal to a non-informative prior, reflecting total/perfect ignorance about the true class distribution?

If we assume as likelihood _L_ P(inner_classifier predicts class 0 | true class is 0) = 0.9, and as prior P(true class is 0) = 0.5 (given a hypothetical binary inner_classifier), then the posterior equals (following Bayes' rule)

_L_ * prior / (_L_ * prior + (1 - _L_) * (1 - prior))

= 0.9 * 0.5 / (0.9 * 0.5 + 0.1 * 0.5)

= 0.9 (which totally reflects the inner classifier's "opinion")


In the above case, did you expect the posterior probability for class 0 to have a different value than 0.9?

**Comment by DavidRosen** [comment]
Isn't the likelihood p(X|y), but aren't you using as the likelihood p(y_hat[=0]|y[=0]) where y_hat is the classification given by the inner classifier?

**Comment by jsamoocha** [comment]
> ... I don't understand why instead you seem to be using as the likelihood p(y_hat[=0]|y[=0]) where y_hat is the classification given by the inner classifier?

This is the exact (default) purpose of `SubjectiveClassifier`: it returns the posterior p(y[=0] | y_hat[=0]), given the prior p(y[=0]) and the likelihood p(y_hat[=0] | y[=0]), the latter being computed from the inner classifier's confusion matrix obtained during training.

I hope this at least explains why a uniform prior leads to outcomes that are the same as just using the inner classifier.

**Comment by DavidRosen** [comment]
I was looking for something else, more like this: https://documentation.sas.com/doc/en/emxndg/15.1/p1vqpbjwoo4bv7n1sw77e0z64xxs.htm
