### ISSUE TITLE
[DOCS] Missing line break in documentation

### ISSUE THREAD

**Issue by stephanecollot** [koaning/scikit-lego#202]
Some how the documentation is not displaying new line anymore:

https://scikit-lego.readthedocs.io/en/latest/api/sklego.html?highlight=TimeGapSplit#sklego.model_selection.TimeGapSplit

**Comment by arthurpaulino** [comment]
Hi @stephanecollot!
The link you posted is not working anymore.

**Comment by stephanecollot** [comment]
This was fixed and merged in #227
