### ISSUE TITLE
[FEATURE] Bayesian Encoder -> PandasPipe maybe? 

### ISSUE THREAD

**Issue by arthurpaulino** [koaning/scikit-lego#207]
Encoding categorical features with one hot encoding (basically the only option available on scikit-learn) can be quite troublesome in many scenarios. Something that has been working very well for me lately is a Bayesian approach. For instance, data in this binary classification problem:

```
Column      Class
'value1'    1
'value1'    1
'value1'    0
'value2'    1
'value2'    0
```

Would become:
```
Column      Class
0.667       1
0.667       1
0.667       0
0.5         1
0.5         0
```

0.667 = 2/3 (2 positive cases out of 3)
0.5 = 1/2 (1 positive cases out of 2)

This can also be applied for multi-class problems, generating a new column for each class (except for class 0, which would be redundant).

What do you guys think?

**Comment by MBrouns** [comment]
Hi Arthur,

I think in general such kinds of features would be good, but I wouldn't necessarily call this a bayesian encoder, but maybe a mean encoder instead. For a bayesian encoder I would expect either to be able to set some priors on the distributions per category or that it would use an empirical bayes approach to apply some shrinkage based on the group sizes.

Also, we should keep in mind that there is also this project: http://contrib.scikit-learn.org/categorical-encoding/index.html which has a few of these implemented

What do you think @koanning

**Comment by arthurpaulino** [comment]
> Also, we should keep in mind that there is also this project: http://contrib.scikit-learn.org/categorical-encoding/index.html which has a few of these implemented

Oh, so it's already here: http://contrib.scikit-learn.org/categorical-encoding/targetencoder.html

Thanks!

**Comment by koaning** [comment]
Yeah so that contrib project should have preference over what we do here. I would say that there might be an encoder that is *similar* to what we're describing here. 

Suppose;

```
Column      OtherVal   Class
'value1'    2.5        1
'value1'    3.5        1
'value1'    1.5        0
'value2'    1.0        1
'value2'    2.0        0
```

There might be moments where I'd like to average the `column` with a column that is not the output column. What I'm not sure about though is if this is better solved in pandas or in scikit.

That said, this might be a nice argument to have a PandasPipe() transformer. The benefit would be that we can pass it a function and kwargs that we might gridsearch over. @MBrouns this might actually be a sound idea, no?

**Comment by koaning** [comment]
@arthurpaulino I would mention: that target-encoder is actually a trick that seems to work well a lot of times.

**Comment by MBrouns** [comment]
PandasPipe is definitely a useful feature, although this should probably live in sklearn rather than pandas in order to make sure the mean is nicely calculated on train only

**Comment by arthurpaulino** [comment]
@koaning Just to check if I understood what you meant... would the result of what you said be:

```
Column      OtherVal   Class
2.5         2.5        1
2.5         3.5        1
2.5         1.5        0
1.5         1.0        1
1.5         2.0        0
```
?

**Comment by koaning** [comment]
Ah yes. That's going to be a bit tricky. 

I wonder where the abstraction should be though. I agree that something might go wrong with the `PandasPipeline` in terms of information leakage but I wonder if this responsibility should be deferred to the user.

**Comment by koaning** [comment]
@arthurpaulino I'll edit the comment above.

**Comment by koaning** [comment]
This issue is now supported in sklearn via [FuncTransformer](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.FunctionTransformer.html).
