### ISSUE TITLE
[FEATURE] Contraints on refit choice Gridsearch

### ISSUE THREAD

**Issue by MBrouns** [koaning/scikit-lego#208]
In many cases I'm interested in multiple scoring metrics when doing gridsearch and I generally set hard constraints on the metrics I'm not directly optimizing for.

It would be nice if we could set some of these constraints directly on the gridsearch, rather than getting it out manually through the gridsearch attributes after fitting.

**Comment by koaning** [comment]
It feels like this is best solved by taking the trained gridsearch object and passing it into a function that changes the `.best_estimator_` property as well as the ranking in the `.cv_results_`. I am not sure if we'd want to have a "lego" variant of the gridsearch cv object.

**Comment by MBrouns** [comment]
closing this in favour of continuing the discussion in #210
