### ISSUE TITLE
[FEATURE] conda availability

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-lego#211]
We've noticed for windows users that cvxpy doesn't always install nicely via pip because of the some C++ dependencies. An easy way to solve this is to have the windows users use conda instead since it seems that [cvxpy is available on conda](https://anaconda.org/cvxgrp/cvxpy). 

We'll need to figure out what the easiest path is for this.

**Comment by MBrouns** [comment]
From a users perspective I guess the nicest way forward is for us to provide a windows wheel?

**Comment by maxibor** [comment]
I made a PR to add scikit-lego to conda-forge ([#9958](https://github.com/conda-forge/staged-recipes/pull/9958)) (but I unfortunately can't test it on Windows)

Should I list you as one of the maintainers of the conda package @koaning @MBrouns ?

**Comment by MBrouns** [comment]
Thanks for picking this up! I'll try to see if I can verify whether this works on a restricted windows machine. If you could list both of us that'd be great!

**Comment by maxibor** [comment]
The continuous integration logs are [there](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=83849) :
Seems to be fine on Linux 64, OS X 64, and Windows 64

**Comment by koaning** [comment]
@maxibor @MBrouns at the moment I've kept the distribution on pypi a manual thing and it seems preferable to me to keep it that way. The command to push is in the `Makefile`. If the conda command could be added that'd be grand. 

@MBrouns it might make sense if I figure out a way for you to also be able to push?

**Comment by maxibor** [comment]
AFAIK the distribution through conda-forge is also manual: one needs to submit a PR to update the conda recipe to a new version.

**Comment by MBrouns** [comment]
I verified that the conda installation works today in class on a windows laptop without visual studio so this looks good! Thanks a bunch @maxibor for doing this. If you send me your address somehow  (my email is my github handle @xccelerated.io) I'll send you some stickers.
