### ISSUE TITLE
add --pre-commit features

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-lego#221]
our ci jobs are taking a longer time now and since 25% of the issues are flake related it may be a good idea to add black to this project and force it with a pre commit hook

@MBrouns objections?

**Comment by MBrouns** [comment]
I made a PR that formatted everything with black (#223). I'm gonna go through that to see if I like the style everywhere first

**Comment by koaning** [comment]
I've made a PR that does not contain black just yet but does contain some useful hooks. https://github.com/koaning/scikit-lego/pull/260
