### ISSUE TITLE
feature request: ensemble model that takes p(class | model) into account

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-lego#23]
It might be nice to have an variant of the [voting classifier](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.VotingClassifier.html). One that goes a bit further than mere voting but takes the uncertainty of seperate classifiers into account.

**Comment by koaning** [comment]
700 downloads cant be wrong. 

https://link.springer.com/chapter/10.1007/978-3-319-00651-2_19

**Comment by RensDimmendaal** [comment]
@koaning : How does this proposal differ from setting voting="soft" in [sklearn.ensemble.VotingClassifier](https://scikit-learn.org/stable/modules/generated/sklearn.ensemble.VotingClassifier.html)?

**Comment by koaning** [comment]
I'll make it slightly clearer what I am thinking about here. 

Consider that we have an ensemble of three models. They each have a confusion matrix and at the time of inference they each come with a prediction for class `B`.

![image](https://user-images.githubusercontent.com/1019791/74513307-8e117f00-4f0a-11ea-8cc9-253fceee5f1e.png)

Do we really trust what model A has to say here? When it predicts class `B` then it is often wrong. 

![image](https://user-images.githubusercontent.com/1019791/74513376-b4371f00-4f0a-11ea-84f0-28247830e9f1.png)

So maybe ... we need a different way of reweighting here. An idea I've had for a while is to try to reweigh the weights using the confusion matrix. There is even something bayesian about it. 

![image](https://user-images.githubusercontent.com/1019791/74513430-d03ac080-4f0a-11ea-97c4-5a3544a34e2c.png)
