### ISSUE TITLE
[FEATURE] Combine classifier with outlier detection

### ISSUE THREAD

**Issue by corriebar** [koaning/scikit-lego#233]
I played around with the outlier detection and found that, at least for my data, having an outlier detection that takes group structure into account would be beneficial.

I wrote a small script that uses the classifier to detect outliers per class and then took the mean of the outlier detection. That is, all points that are classified as outliers for most/all classes are then outliers. (I mostly copy/pasted from the OutlierDetector)

``` python
from sklearn.datasets import make_blobs
from sklego.mixture import BayesianGMMClassifier
from scipy.stats import gaussian_kde
from scipy.optimize import minimize_scalar

n_samples = 500
centers = [(-5, -5), (0, 0), (5, 5)]
X, y = make_blobs(n_samples=n_samples, n_features=2, cluster_std=1.0,
                  centers=centers, shuffle=False, random_state=42)

clf = BayesianGMMClassifier()
clf.fit(X, y=y)
```
Using some code from OutlierDetector:
``` python
# using percentile method
threshold = 0.95
res = np.zeros((X.shape[0], clf.classes_.shape[0]))
for idx, c in enumerate(clf.classes_):
    res[:, idx] = clf.gmms_[c].score_samples(X)

for idx, c in enumerate(clf.classes_):
    # compute likelihood threshold only based on points in class
    score_samples = res[y==c, idx]
    likelihood_threshold_ = np.quantile(score_samples, 1 - threshold)
    
    # but offset by threshold for all points
    res[:, idx] = -res[:,idx] + likelihood_threshold_

predictions = (res >= 0).astype(int)

y_hat = clf.predict(X)
outlier_thres = 0.9       # point is outlier if it is outlier for 
                                    # more than 90% of classes
predm = np.where(predictions.mean(axis=1) > outlier_thres, -1, y_hat)
for i in range(-1, len(clf.classes_)):
    plt.scatter(X[predm == i,0], X[predm == i,1], label=i)
plt.legend()
plt.show()
```
![image](https://user-images.githubusercontent.com/11877945/67684188-fc99f380-f992-11e9-91e6-cfb51d460f6d.png)

What do you think?

**Comment by koaning** [comment]
You certainly have a reasonable idea there but I our library would use a slightly different pattern: meta-models. In particular the [GroupedEstimator](https://scikit-lego.readthedocs.io/en/latest/meta.html#Grouped-Estimation). 

## The Idea

Scikit-Lego features *lots* of meta-models. A meta model behaves like a decorator of sorts. It adds behavior to the underlying model. 

The idea behind the grouped estimator is that you can tell a model to train per subset. The subset would be defined via a column in the data `X`. This column will not be used during training but it will be used to split the dataset into separate parts. I've made a small drawing of how that might work in a pipeline for this problem. 

<img width="704" alt="Screenshot 2019-10-28 at 19 49 12" src="https://user-images.githubusercontent.com/1019791/67708220-0edc5780-f9bc-11e9-9e08-29f0e5991e53.png">

The part that I like about this is that it separates concerns. If you have another outlier detector model (`BayesianGMMDetector` or `IsolationForest`) you can use it just as well. Also note that our approach still allows for a gridsearch. The only thing that you need to do is that you need to add `y` to `X` beforehand. 

Does this make sense? 

### Also 

I gotta say, I certainly wouldn't mind having this example in the docs if you're up for it.

**Comment by koaning** [comment]
## Small Misread 

After re-reading your post I realize that what I am offering is slightly different to what you're doing. 

There's a feature on our roadmap which is the `WontPredict` meta-estimator. We haven't figured it out yet but the idea is that you offer your estimator and a `judge` that determines if the point to be predicted needs to receive the `WontPredict` flag. For context you might appreciate [the first 20 minutes of this pydata talk](https://www.youtube.com/watch?v=Z8MEFI7ZJlA). 

<img width="676" alt="Screenshot 2019-10-28 at 19 56 43" src="https://user-images.githubusercontent.com/1019791/67708935-59aa9f00-f9bd-11e9-84c1-1cb9ae89100f.png">

The `WontPredict` meta model has not been implemented yet and requires a discussion. You're more than welcome to join it.

**Comment by MBrouns** [comment]
Cue me writing a large story twice and deleting it just after seeing @koaning's reply. I think this makes the most sense as a `WontPredict` meta-estimator that (in the specific case of @corriebar) uses a GMMClassifier as the estimator and a GMMOutlierDetector as the referee.

**Comment by corriebar** [comment]
Ah so the GroupedEstimator is similar to using map/nest/model in R. neat.

The WontPredict is indeed closer to what I'm doing. I actually thought something like this was already part of your package after seeing the talk :sweat_smile: 

The WontPredict is def more flexible for using different combos of estimators/referees. What I like about my approach using Gaussian Mixture, is that the same method is used for classification and outlier detection. Also, note that getting the outlier from the grouped data gives different results than applying outlier detection afterwards/separately. Though not sure the difference is significant in practice.
Happy to join the WontPredict discussion

**Comment by koaning** [comment]
> Ah so the GroupedEstimator is similar to using map/nest/model in R. neat.

There's a reason why I felt the need for this in python; I loved this feature in R. 

I'll close this discussion for now then. Feel free to join the other discussion. Also, if you feel like adding your example to the docs: I'll gladly accept it.
