### ISSUE TITLE
[BUG] 13 tests are failing in the master branch

### ISSUE THREAD

**Issue by greatsharma** [koaning/scikit-lego#248]
In order to help us fix a potential bug we need: 

- [ ] a clear and concise description of what the bug is.
- [ ] code that helps us reproduce this 
- [ ] **optional** a unit test that helps us catch the bug in the future

**Comment by koaning** [comment]
Yeah we are aware of it. We didn't fix it because of the holiday season and we're assuming this is due to a new scikit-learn release. 

No worries though, it was on our radar ;)

**Comment by greatsharma** [comment]
Is it compulsory to raise an issue before PR for small changes?

**Comment by MBrouns** [comment]
Typo's etc. are fine without issues, but in general I would raise an issue beforehand just to avoid doing redundant work

**Comment by koaning** [comment]
These now look green.
