### ISSUE TITLE
Code Correction and enhancement in some of the preprocessing classes

### ISSUE THREAD

**Issue by greatsharma** [koaning/scikit-lego#249]
I suggests the following changes to preprocessing classes -

1.  Originally In transform method of PandasTypeSelector, 
	_check_X_for_type(X) is called after checking dtypes. By this 
	if we call transform method on numpy array then it raise
        `AttributeError: 'numpy.ndarray' object has no attribute dtypes`
	
	but _check_X_for_type(X) should be called before checking dtypes,
	and then calling transform on numpy array raises
       `TypeError: Provided variable X is not of type pandas.DataFrame`

	which is the suitable and correct error message to user.

2. In class ColumnSelector - 
	- The following if statement should be moved from fit to init method
                `if not isinstance(self.columns, list):
                        self.columns = [self.columns] `
	
	 this is done for two reasons first to make the code consisent with 
	 other similar classes(in this case ColumnDroper class). And second
	 because this checking is suitable during class instantiation and
	 has nothing specific to fit method.

 	-  call _check_X_for_type(X) in the transform method, because this
	   class is dedicated to DF only and checking X type in fit is not
	   sufficient because if we fit a DF but try to transform an array
	   then it throws,
		`IndexError: only integers, slices (`:`), ellipsis (`...`),
                    numpy.newaxis (`None`) and integer or boolean
                    arrays are valid indices`

	  but the more suitable and correct error would be,
		`TypeError: Provided variable X is not of type pandas.DataFrame`

3. In class OrthogonalTransformer - 
	let's take a df with columns ['a', 'b', 'c', 'd']

	- Originally if we fit df[['a', 'b']] but transform df[['c', 'd']]
	  or df[['b', 'a']] then it just runs the code, but the returned 
	  results will be incorrect because we fit and transform 2 DFs with
	  different columns. But we need not to be worried in case of numpy
	  arrays as there is nothing like column names.

	Such transformation should be handled with raising following error, 
	`KeyError: Columns were not equal during fit and transform`

4. In class ColumnDroper -
	- In transform method call check_is_fitted otherwise
         get_feature_names() will throw attribute error if we call it on
	  object which is transformed without fitting.

	- In transform method call check_X_for_type() for the same reason
	  I explained for ColumnSelector class above.

**Comment by koaning** [comment]
1. Happy new year!
2. Thanks, you really seem to put effort in here.
3. Could you split these points into separate issues? Might make it easier to keep the discussion clean.
