### ISSUE TITLE
redundant if and attribute in PandasTypeSelector

### ISSUE THREAD

**Issue by greatsharma** [koaning/scikit-lego#261]
`self.type_columns_`  and `self.feature_names_` always evaluates to the same thing hence `self.type_columns_` seems to be redundant. 

Also the following if in transform() always evaluates to `False` 
```
if set(list(transformed_df)) != set(self.type_columns_):
      raise ValueError(f'Columns were not equal during fit and transform')
```
because we already checked for `if (self.X_dtypes_ != X.dtypes).any()` and whenever columns differ during fit and transform this checking will automatically raise `ValueError: Can only compare identically-labeled Series objects`

but if we want to be more descriptive to the user then we can wrap this dtype checking in `try` block.
and raise `ValueError: Columns were not equal during fit and transform`

the code looks like this after these changes: 
```
    def fit(self, X, y=None):
        self._check_X_for_type(X)
        self.X_dtypes_ = X.dtypes
        self.feature_names_ = list(X.select_dtypes(include=self.include, exclude=self.exclude).columns)

        if len(self.feature_names_) == 0:
            raise ValueError(f'Provided type(s) results in empty dateframe')

        return self

    def get_feature_names(self, *args, **kwargs):
        return self.feature_names_

    def transform(self, X):
        check_is_fitted(self, ['X_dtypes_', 'feature_names_'])

        try:
            if (self.X_dtypes_ != X.dtypes).any():
                raise ValueError(f'Column dtypes were not equal during fit and transform. Fit types: \n'
                                 f'{self.X_dtypes_}\n'
                                 f'transform: \n'
                                 f'{X.dtypes}')
        except ValueError:
            raise ValueError(f'Columns were not equal during fit and transform')

        self._check_X_for_type(X)
        transformed_df = X.select_dtypes(include=self.include, exclude=self.exclude)

        return transformed_df
```
I worked on this and after these changes the behaviour remains the same.

If I am missing something please point, else I would like to make a PR

**Comment by greatsharma** [comment]
@MBrouns please review this, I checked this out.

**Comment by MBrouns** [comment]
Yep, seems to make sense! I do like the explicit error rather than the 'can only compare identically labeled series'. It might even make sense to add the diff between the series indices in that error, but other than that it looks good

**Comment by greatsharma** [comment]
@MBrouns are you requesting some changes? Because it's not clear to me.

To add the diff between the series indices in that error would require transformed_df beforehand which is not possible and even if we did that then I think it make the code more complex, lossing it's main logic/functionality and overcasting the error handling only. Still if you have any idea then tell me I will do because may be I am missing something or it's not clear to me.

But I urge to retain the same error as you guys did before i.e.,  `ValueError: Columns were not equal during fit and transform` and this kind of error is thrown at other places like in `ColumnCapper`
