### ISSUE TITLE
[FEATURE] BaselineDropnan 

### ISSUE THREAD

**Issue by greatsharma** [koaning/scikit-lego#268]
BaselineDropnan can be the first tool for the users while handling `nan` data. In majority of cases the data contains `nan` so we can create a baseline model to know how it behaves on removing all nan rows/columns (provided by the user). The idea is just to get a quick first look on nan data or for a good initial baseline in one liner code. 

The API looks like this : 
```
class BaselineDropnan(BaseEstimator):

    def __init__(self, estimator, axis=1):
        self.estimator = estimator
        self.axis = axis

    def fit(self, X, y) :
        y = check_array(y, ensure_2d=False)
        if len(y) == 0:
            raise ValueError("y must not be empty.")
        
        check_consistent_length(X, y)

        X_tf, y_tf = self._remove_nan_axis(X, y)
        self.dim_ = X_tf.shape[1]

        self.estimator_ = clone(self.estimator)
        self.estimator_.fit(X_tf, y_tf)

        return self

    def _remove_nan_axis(self, X, y):
        self.nans_ = np.isnan(X).any(axis=self.axis)
        if all(self.nans_):
            raise ValueError(f'Dropping nan along axis {self.axis} results in empty X')

        if self.axis:
            X_tf = X[~self.nans_]
            y_tf = y[~self.nans_]
        else:
            X_tf = X[:, ~self.nans_]
            y_tf = y

        return X_tf, y_tf

    def predict(self, X):
        check_is_fitted(self, ['dim_', 'nans_', 'estimator_'])
        X = check_array(X, estimator=self, dtype=FLOAT_DTYPES)

        if X.shape[1] != self.dim_:
            raise ValueError(f'Unexpected input dimension {X.shape[1]}, expected {self.dim_}')

        return self.estimator_.predict(X)
```

Usecase would be like this : 
```
from sklego.dummy import BaselineDropnan

est = LogisticRegressionCV(max_iter=1000)
model = BaselineDropnan(est, axis=1).fit(Xnan_train, y_train)

yhat = model.predict(X_test)
classification_report(y_test, yhat)
```

**Comment by koaning** [comment]
Just so I understand, what is the `BaselineDropnan` supposed to do? I think dropping rows that contain a `NaN` is a bad idea in general.

**Comment by koaning** [comment]
Here's the doozy. Suppose that I have an `X` that has some number of rows that contain missing values. As a user, you typically don't know how many exactly. So let us presume that the initial dataset has 1000 rows, 50 out of which contain NaNs. 

Let's then say that we have a model that produce a prediction `y_hat` containing 950 rows. How will the user be able to link these predictions back to their corresponding rows in `X`?

**Comment by koaning** [comment]
I also think that `NaN`s tend to be something that has a lot of context. Context which doesn't really translate well into a general tool that is supposed to work across usecases.

**Comment by greatsharma** [comment]
> Here's the doozy. Suppose that I have an `X` that has some number of rows that contain missing values. As a user, you typically don't know how many exactly. So let us presume that the initial dataset has 1000 rows, 50 out of which contain NaNs.
> 
> Let's then say that we have a model that produce a prediction `y_hat` containing 950 rows. How will the user be able to link these predictions back to their corresponding rows in `X`?

In that case user can get the nan rows using `self.nans_` and `yhat` containing 950 rows corresponds to `X[~self.nans_]`

**Comment by greatsharma** [comment]
> Just so I understand, what is the `BaselineDropnan` supposed to do? I think dropping rows that contain a `NaN` is a bad idea in general.

It's indeed a bad idea but it is for baseline like `RandomRegressor`, just to get a quick idea about data and model. And also when `nan` rows are less it sometimes gives good starting model.

**Comment by koaning** [comment]
> > Just so I understand, what is the `BaselineDropnan` supposed to do? I think dropping rows that contain a `NaN` is a bad idea in general.
> 
> It's indeed a bad idea but it is for baseline like `RandomRegressor`, just to get a quick idea about data and model. And also when `nan` rows are less it sometimes gives good starting model.

In that case it'd still be better to impute, no?

**Comment by greatsharma** [comment]
Hmm,  agree but also imputation is a part of data preprocessing and in `dummy.py` we provide very basic baseline start. Also there is a lot to do in imputation.

**Comment by koaning** [comment]
Imputation is largely handled by transformers in sklearn. There's even a [KNN](https://scikit-learn.org/stable/modules/generated/sklearn.impute.KNNImputer.html)-variant these days. If you have a clear and practical imputation strategy that isn't handled by scikit-learn then I'd be all ears but dropping `NaN`s is bad general practice that I wouldn't want to endorse. 

It also deserves to be said that the `RandomRegressor` isn't really a transformer that needs to be taken *that* serious. It's theoretically meant to be pretty much one of the worst models out there. 

If I am misinterpreting what you're trying to achieve let me know. Feel free to convince me but I am currently not convinced that `NaN` dropping is something worth maintaining. @MBrouns thoughts?

**Comment by koaning** [comment]
I will close the issue for now.

**Comment by MBrouns** [comment]
Changing the length of dataframes / array is not something that is common in sklearn. Also, how would the model make predictions for observations containing nans?

I feel this is better left outside of sklearn and more easily handled with a pandas dropna
