### ISSUE TITLE
[BUG] ColumnSelector not working with GridSearchCV

### ISSUE THREAD

**Issue by janvdvegt** [koaning/scikit-lego#269]
When using a GridSearchCV with the ColumnSelector it throws an error about not being able to clone the ColumnSelector:

```RuntimeError: Cannot clone object ColumnSelector(columns=['x1']), as the constructor either does not set or modifies parameter columns```

This was with and without the reference to the object in the param_grid:

    param_grid = {"dummyclassifier__strategy": ["constant"],
                  "dummyclassifier__constant": [1],
                  "columnselector__columns": [["x1"]]}
    pipeline = make_pipeline(
        ColumnSelector('x1'),
        DummyClassifier())
    accuracy_x1_0 = subset_score(lambda X, y_true: X['x1'] == 0, accuracy_score)

    cv = DisabledCV()
    search = GridSearchCV(estimator=pipeline, param_grid=param_grid, scoring=accuracy_x1_0, cv=cv)

    X, y = slicing_classification_dataset
    search.fit(X, y)

At the `.fit` method it actually throws the error.

**Comment by koaning** [comment]
We had noticed this bug a while ago and we fixed it. What we haven't done in the meantime is do a release. I'll do that now. Within 15 minutes you should be able to install again. If the error persists: do let us know!

**Comment by koaning** [comment]
It should now be live https://pypi.org/project/scikit-lego/
