### ISSUE TITLE
[FEATURE] Monotonic Regression API

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-lego#277]
@MBrouns and myself have already agreed that we want to have monotonic regression/classification in this project. What we should probably discuss is the API. 

We'd like to be able to select columns to constrain on as well as how. One proposal could be;

```
ConstrainedRegression(alpha=0.001, positive=[0, 1], negative=[4])
```

Another one could be. 

```
ConstrainedRegression(alpha=0.001, constraints={0: 1, 1: 1, 4: -1})
```

Something inside of me prefers to former. It feels like we do not need to explicitly label all columns, only the ones that require a constraint.

**Comment by koaning** [comment]
There's also the matter of dataframes, but that seems solvable by allowing for strings in the dictionary/list.

**Comment by MBrouns** [comment]
Regarding monotonicity, XGBoost does the following:

```
Some other examples:
(1,0): An increasing constraint on the first predictor and no constraint on the second.
(0,-1): No constraint on the first predictor and a decreasing constraint on the second.
```

While I'm not necessarily convinced that that is the best way, there is something to say for keeping it compatible.

The first suggestion could theoretically allow a misspecification where a colum is both positive and negative.

The second approach allows for easy compatibility with the xgboost method. Pass a dictionary and it behaves like you have it now, pass another iterable you get the xgboost behaviour

**Comment by koaning** [comment]
Anything against allowing both? The misspecification can be dealt with via `ValueError`.

**Comment by MBrouns** [comment]
Sure, that seems ok!
