### ISSUE TITLE
[BUG] Interval Encoder ... how to deal with edge quantiles

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-lego#285]
There's the effect of using the `IntervalEncoder`. 

It works swell ... but! ... look at the top left example ... 

![image](https://user-images.githubusercontent.com/1019791/74087569-eb7e7980-4a8d-11ea-91ab-b16cbfb2bb98.png)

Do we really like that jump the orange line does there at the end? It feels like maybe when we create these quantiles we should maybe artifically remove the outer ones ... there's a risk of overfitting when we attempt something monotonic there.

**Comment by MBrouns** [comment]
It's an interesting behaviour, which I wouldn't really expect as the amount of observations for each interval should be the same. 

Dropping the outer intervals seems a bit drastic though. Could adding a `median` method next to the `average` and `normal` help here?

**Comment by koaning** [comment]
Sure, but it's not those methods that I'm worried about. It's the monotonic ones ...

**Comment by MBrouns** [comment]
ugh yea my bad, it's late apparently

**Comment by koaning** [comment]
No worries. I do wonder about a neat solution for that issue though. Removing outer quantiles might be an ok thing to do.
