### ISSUE TITLE
[BUG] `give_pandas` to become `as_frame`

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-lego#287]
Currently our API uses `give_pandas=True` if we want to return the pandas dataframe. Scikit-learn has chosen for [another standard](https://scikit-learn.org/dev/whats_new/v0.23.html#sklearn-datasets). We should follow theirs. 

![image](https://user-images.githubusercontent.com/1019791/74109428-b2c0cc00-4b83-11ea-84f9-9504f9898b0a.png)

**Comment by MBrouns** [comment]
fixed in #349
