### ISSUE TITLE
[DOCS] datasets are currently undocumented

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-lego#288]
It would be nice to have a notebook that shows a plot and a few rows of all the datasets that we have.

**Comment by koaning** [comment]
The API lists the datasets, which is good, but it would improve the documentation if there was a small overview available as well. Maybe just showing the first few rows and maybe a plot. Nothing too fancy but enough to get somebody new up to scratch very quickly.

**Comment by nvanommeren** [comment]
Hello! I just submitted a merge request and still have a question:

- There is a notebooks folder inside the docs folder, but there are also many notebooks outside of this folder. What is the preferred location for the datasets notebook? 

Let me know if you have any feedback.

**Comment by koaning** [comment]
This issue is now fixed.
