### ISSUE TITLE
[FEATURE] add the HEARTS dataset

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-lego#289]
The [tensorflow lattice documentation](https://www.tensorflow.org/lattice/tutorials/keras_layers) links to a [dataset](http://storage.googleapis.com/applied-dl/heart.csv) that might be nice to add to our little library. It might be good to demonstrate the merit of adding monotonic constraints.

**Comment by koaning** [comment]
Turns out it orignally was found [here](https://archive.ics.uci.edu/ml/datasets/Heart+Disease).

**Comment by kayhoogland** [comment]
https://github.com/koaning/scikit-lego/pull/345
