### ISSUE TITLE
[DOCS] ProbWeightRegressor needs documentation

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-lego#294]
We have the api [here](https://scikit-lego.readthedocs.io/en/latest/api/API%20Reference.html#sklego.linear_model.ProbWeightRegression) but it would be nice to add an example of it.

**Comment by kaipoethkow** [comment]
The updated link is https://scikit-lego.readthedocs.io/en/latest/api/linear_model.html#sklego.linear_model.ProbWeightRegression .

But I found an example here https://scikit-lego.readthedocs.io/en/latest/linear-models.html#ProbWeightRegression so I guess this issue can be closed.

**Comment by koaning** [comment]
Well spotted! Yes, I've since added a page.
