### ISSUE TITLE
[DOCS] preprocessing API gone

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-lego#295]
Probably when we preprocessing part of the library got split up into a folder we forgot to make sphinx aware of it. Docs look like this now; 

![image](https://user-images.githubusercontent.com/1019791/74315460-c3d22e80-4d77-11ea-8a84-23d159443edc.png)

**Comment by tomasborrella** [comment]
I was looking for a good first issue to contribute, and I've found this one, but it seems to be fixed in the current version, isn't it?

**Comment by koaning** [comment]
You'd be correct. There's still some work to be done in the docs though. 

For example; it'd be nice if the API wasn't a long list on a single page, but something more like [this](https://scikit-fairness.netlify.app/api/datasets.html). Fixing that requires an understanding of rst though. 

Another idea; run `codespell` on our docs to see if there's a common spelling error in the docs (odds are that there's one or two in the code too). 

Also: feel free to skip this one in favor of another "good first issue".

**Comment by koaning** [comment]
If instead you spot something in the docs that could be made "more clear": feel free to comment on that.

**Comment by tomasborrella** [comment]
I like your project and I'd like to be able to help out, so I'll take a look at the two points you mention to start with: 
+ `ReStructuredText` to try to make API section nicer.
+ `codespell` project for to look for misspellings

Do you think is it a good idea to open new issues for those two points and close this issue? (just for clarity) or do we keep the conversation here?

**Comment by koaning** [comment]
You are free to turn those into issues, once you've done that I'll close this one.

**Comment by tomasborrella** [comment]
Cool! I've created the two isues:
[#326](https://github.com/koaning/scikit-lego/issues/326) 
#327 

So you can close this one. I'll started working on one of them during the weekend :)
