### ISSUE TITLE
[FEATURE] hall of fame

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-lego#296]
if we're gonna do a sprint someday, it might be nice to add a hall of fame. feature? 

https://github.com/sourcerer-io/hall-of-fame

**Comment by koaning** [comment]
I have some concerns about this now. 

1. There's something to be said about a clean readme. It welcomes newbies who want to learn the tool and I fear that such a hall of fame is going to be distracting. 
2. It may be better though if we add something to the documentation.

**Comment by koaning** [comment]
Will assign @pverheijen

**Comment by Pverheijen** [comment]
Hi there,

I've added a separate page for Hall of Fame in the docs. 
Furthermore I've added this separate page to the index. 

Pull request that contains these changes: 
Addded Hall of Fame to the docs under contribution

@Mbrouns thank you for helping

**Comment by koaning** [comment]
Reminder (for me) to look at this later: https://allcontributors.org/.
