### ISSUE TITLE
[BUG] conda does not update automatically

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-lego#297]
@MBrouns dunno if we want to automate this, but can you push to conda?

**Comment by MBrouns** [comment]
There's an automatic PR in the feedstock project that needs to be merged (https://github.com/conda-forge/scikit-lego-feedstock/pull/2). Do you get those notifications as well? I think we could automate that but as it doesn't auto-update dependency changes I'm not sure we should

**Comment by koaning** [comment]
Ah. I'll watch that. 

Doing that manually seems fine.
