### ISSUE TITLE
[DOCS] There's no mention of the datasets in the docs

### ISSUE THREAD

**Issue by MBrouns** [koaning/scikit-lego#299]

**Comment by koaning** [comment]
The goal would be to have a page added here;

![image](https://user-images.githubusercontent.com/1019791/76686256-5f2a1e00-661a-11ea-9748-f68eaa03586c.png)

**Comment by tomasborrella** [comment]
There is datasets information inside "API Reference" section. Do you think is it still interesting having a page in the first level of contents? It would be the same that is inside API rigth now or are you thinking of something different?

NOTE: There is another issue regarding Datasets #288 , but I don't know if it is out of date.

**Comment by koaning** [comment]
I would argue they are the same issue. I'll close down this one since the API indeed technically fixes this. Will leave the other one open.
