### ISSUE TITLE
feature request: loess/lowess regression 

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-lego#3]
I've always wanted to have loess regression in python. R has a cool version of it but it has always been missing. This would be a great model to host here.

**Comment by koaning** [comment]
The easiest way to explain what it needs to do: 

![](https://raw.githubusercontent.com/simplystats/simplystats.github.io/master/_images/loess.gif)

**Comment by dvanamstel** [comment]
DIBS

**Comment by tsuhina** [comment]
Second that

**Comment by koaning** [comment]
```
library(tidyverse)

df <- data_frame(xs=1:120, ys=10*sin(xs/10) + rnorm(120, 0, xs/10)) %>% 
  filter(ifelse((xs < 100) & (xs > 75), FALSE, TRUE))

ggplot() + 
  geom_point(data=df, aes(xs, ys)) + 
  geom_smooth(data=df, aes(xs, ys), span=0.5)
```

![image](https://user-images.githubusercontent.com/1019791/54868719-dde5d580-4d8f-11e9-9020-8b60924940ef.png)

**Comment by koaning** [comment]
```
ggplot() + 
  geom_point(data=df, aes(xs, ys)) + 
  geom_smooth(data=df, aes(xs, ys), span=0.1)
```

![image](https://user-images.githubusercontent.com/1019791/54868725-eccc8800-4d8f-11e9-9362-ccf11d48c718.png)

**Comment by koaning** [comment]
```
ggplot() + 
  geom_point(data=df, aes(xs, ys)) + 
  geom_smooth(data=df, aes(xs, ys), span=1)
```

![image](https://user-images.githubusercontent.com/1019791/54868727-f48c2c80-4d8f-11e9-9ee9-7d560ccd057d.png)

**Comment by koaning** [comment]
http://web.ipac.caltech.edu/staff/fmasci/home/astro_refs/LocalRegressionBook_1999.pdf

**Comment by dvanamstel** [comment]
Nice book, thanks!

I expect to have a few hours next week to finish up what we started.

**Comment by koaning** [comment]
It seems to be in statsmodels. Maybe it is not a right fit.
