### ISSUE TITLE
[FEATURE] boston housing

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-lego#300]
sklearn wants to get rid of it ... should we have it as a fairness lesson?

**Comment by koaning** [comment]
we should. but the docs/docstring need to explain the controversy clearly.

**Comment by timvink** [comment]
Good background article: https://medium.com/@docintangible/racist-data-destruction-113e3eff54a8

You already mention what `B` stands for in https://scikit-lego.readthedocs.io/en/latest/fairness.html#Measuring-fairness-for-Classification. 

What contribution are you looking for specifically?

**Comment by koaning** [comment]
Scikit Learn will remove the boston housing dataset because of the controversy. This is a good thing too. It should not serve as a dataset that demonstrates how easy it is to get started with machine learning. 

It *does* serve as a dataset that demonstrates the danger though. Which is why we were thinking of adding it here. 

It should be said though, there's a new effort that we've started. One that hopefully can become part of the official scikit-learn-contrib. We've called it [scikit-fairness](https://github.com/koaning/scikit-fairness).

**Comment by koaning** [comment]
If you're interested in contributing on this issue -> let me know. It sould just be the addition of the dataset to the scikit-fairness repo.

**Comment by xalelax** [comment]
It sounds interesting, is this still up for grabs? Should one contribute to this issue or to scikit-fairness directly ( https://github.com/koaning/scikit-fairness/issues/16 )?

**Comment by koaning** [comment]
Scikit-Fairness is in flux at the moment. There's some similar projects and we need to check where to consolidate it. If you're interested in making a PR in general, I might advice another issue. If you're set on doing this, then fairness seems preferable for now.

**Comment by timvink** [comment]
> If you're interested in contributing on this issue -> let me know. 

Sorry for the late reply. I was -- then realised I took up a bit too much OS work on the side.

**Comment by koaning** [comment]
@xalelax are you interested in creating the PR for boston on scikit-fairness or is this something that i can pick up?

**Comment by xalelax** [comment]
@koaning sorry, I read that just now. I am interested, but quite swamped at the moment, so I cannot work on it. Pick this up if you want!

**Comment by koaning** [comment]
@xalelax No worries. @MBrouns will implement this on the fairness side.

**Comment by koaning** [comment]
It has now been added to the fairness repo.
