### ISSUE TITLE
[FEATURE] scikit-fairness

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-lego#303]
I've been mulling over this for a while. 

If we want to make it *easy* for people to use fairness algorithms ... should we not have a scikit-fairness under scikit-contrib? It's not just that this might make it easier for folks to pick up but it would also gather attention of folks who are interested in benchmarking. This would be amazing in terms of robustness. If there's a crowd vetting the software, it becomes more reliable. 

What we're doing here with scikit-lego lego is cool ... but in terms of reach ... we may be doing ourselves a bit short by keeping these algorithms here. The goal of this library is to have a cool test-bed for less-standard approaches. But when it comes to fairness ... maybe that deserves a package of it's own. 

@MBrouns what do you think?

**Comment by koaning** [comment]
There's also the argument of making tools that are specific. Scikit-lego has a small risk of becoming a bit too "broad".

**Comment by MaxHalford** [comment]
Big +1 from me. There's already some tentatives at libraries, such as [AIF360](https://github.com/IBM/AIF360). There's also a lot of bits of code scattered around GitHub. However I don't believe I've seen a clear library with a nice API design.

**Comment by MBrouns** [comment]
Yep I like it too. Good to keep this library smaller and add something that's more focussed

**Comment by koaning** [comment]
It might be good for some of us have a peek at [the onboarding form](https://github.com/scikit-learn-contrib/scikit-learn-contrib/blob/master/workflow.md).

**Comment by koaning** [comment]
It is my understanding that we'll now have an in-person meeting on tuesday. It might be good to have a look at packages that try to do something similar before we meet. 

- https://github.com/IBM/AIF360
- https://github.com/dssg/aequitas
- https://github.com/fairlearn/fairlearn

**Comment by fhr** [comment]
Thanks for the mention @koaning . I think there are a lot in the DataKind volunteer community who'd be well placed to contribute, as they're interested & skilled in the intersect between code and fairness questions. Maybe lmk after your in person meeting if that still seems like it would be helpful. 

Also, the document I referenced before (https://www.turing.ac.uk/sites/default/files/2019-06/understanding_artificial_intelligence_ethics_and_safety.pdf) as a potential "rigorous source" for a framework for thinking about this stuff, recommended several tools, which look like they're mainly the same ones you've already picked up: probably good news if there's consensus on what the best so far looks like:

https://dsapp.uchicago.edu/projects/aequitas/ (University of Chicago’s open source bias audit toolkit for machine learning developers)
http://www.fairness-measures.org/ and https://github.com/megantosh/fairness_measures_code/ (Datasets and software for detecting algorithmic discrimination from TU Berlin and Eurecat)
https://github.com/columbia/fairtest (Fairtest unwarranted association discovery platform from Columbia University)
http://aif360.mybluemix.net/# (IBM’s Fairness 360 open source toolkit)

**Comment by koaning** [comment]
@fhr the meeting I mentioned we'd have on tuesday is virtual now. i just got an email from Qcon that made me consider virtual is best for now. don't feel oblidged but you're welcome to join if you're interested.

**Comment by fhr** [comment]
thanks, invite would be v welcome.

**Comment by koaning** [comment]
@fhr could you send me your email via a personal message on linkedin?

**Comment by koaning** [comment]
Closing this issue now. We've decided to port our fairness tools to [fairlearn](https://fairlearn.github.io/). The tools will still be hosted here but we figured it better to merge our tools to a project with more attention from maintainers.
