### ISSUE TITLE
[DOCS] Call out to some more existing academic classifications of fairness in the docs about this section

### ISSUE THREAD

**Issue by fhr** [koaning/scikit-lego#306]
I'm really pleased that you're building these tools and have put in so much work already, it looks great. 

I think that the discussion of "fairness" in this section could be further expanded and structured in an audience-friendly way, and would suggest e.g. using the overview framework starting from p18 of https://www.turing.ac.uk/sites/default/files/2019-06/understanding_artificial_intelligence_ethics_and_safety.pdf as a structure (this is based off of a survey of a bunch of other academic work, so saves reinventing the wheel). I suspect using this thinking framework might also highlight some other new functions that you would then want to build. 

If helpful, I'd be happy to have a stab at drafting appropriate text for this and seeing where it takes us.

**Comment by koaning** [comment]
Hi @fhr nice to see ya here after Qcon :) 

Have you seen [this discussion](https://github.com/koaning/scikit-lego/issues/303)? We're considering taking the fairness parts out of scikit-lego and putting them into a new effort: scikit-fairness. The hope is that this might attract more people to collaborate and it could be an official contrib package. 

Personally, I'm super interested in what you're mentioning here ... it's just that I don't know if this is something that will have to wait until we get the scikit-fairness ball rolling.

**Comment by koaning** [comment]
After thinking about it ... I might need to rephrase that differently. 

@fhr would you, or do you know folks who might, be interested in helping out with a project like scikit-fairness. I certainly imagine that your connection to datakind might help here.

**Comment by fhr** [comment]
@koaning I hadn't seen that discussion. I think it makes a lot of sense to take this out into a different effort, as it's of a quite different type to scikit-lego and will hang together on its own IMO. 

I definitely think that the Datakind community would be very interested. What's a good way to get them involved - point them to a repo? Ask for specific skills? There is an active fairness and ethics book club and lots of people tinkering and coding, so I think there would be a good response if we can suggest ways to focus effort.

**Comment by koaning** [comment]
I am having an in-person meeting on tuesday about the formal steps. I'll keep you in the loop. 

I can certainly imagine on the documentation/content side of things, say examples of datasets with issues and tricks to go about them, Datakind has a lot to offer. I was planning on adding content on [calmcode.io](calmcode.io) but it might be a good idea to perhaps add course material for meetups who want to play around with these tools.

Feel free to join the [discussion](https://github.com/koaning/scikit-lego/issues/303) if you have any feedback.

**Comment by koaning** [comment]
I'm closing this issue. It seems that in the longer term [this project](https://fairlearn.github.io/) should host this feature more than here.
