### ISSUE TITLE
[FEATURE] Add make_debug_pipeline

### ISSUE THREAD

**Issue by Pverheijen** [koaning/scikit-lego#308]
I'd like to see the make_debug_pipeline function added. 
(make_pipeline from scikit-learn is also missing, but that's just copy paste I guess.

I'd like to work on it in my spare time to get more familiar with contributing to open source projects.

**Comment by koaning** [comment]
Just so I understand ... what do you mean with `make_pipeline` from scitkit-learn is also missing?

**Comment by koaning** [comment]
That said ... I don't see a reason not to also include `make_debug_pipeline`. Just pinging @MBrouns @JCZuurmond in case.

**Comment by Pverheijen** [comment]
Never mind the make_pipeline, mistake from my side. We can just import it from sklearn...

**Comment by MBrouns** [comment]
Aye we discussed this in a training last week, I'm +1 for adding a make_debug_pipeline

**Comment by koaning** [comment]
Cool. In that case, @Pverheijen go right ahead and let us know when you appreciate a review.

**Comment by Pverheijen** [comment]
Could some review my pull request for this feature?
[https://github.com/koaning/scikit-lego/pull/311](url)

("Implemented make_debug_pipeline in sklego.pipeline and fixed a bug #311")

Thank you in advance!
