### ISSUE TITLE
[DOCS] Make API section nicer

### ISSUE THREAD

**Issue by tomasborrella** [koaning/scikit-lego#326]
It would be nice if the API wasn't a long list on a single page, but something more like [this](https://scikit-fairness.netlify.app/api/datasets.html). 

Fixing that requires an understanding of rst though.

**Comment by koaning** [comment]
If you haven't started yet, it may be good to delay this issue until https://github.com/koaning/scikit-lego/pull/331 is merged. Instead of having everything in a big file we're moving things to folders. This may have an effect on the API section.

**Comment by tomasborrella** [comment]
Cool, I'll wait. I'm geting familiar with rst in the mean time.

**Comment by koaning** [comment]
Aaaaaaaaand. It's now approved/merged.

**Comment by koaning** [comment]
Fixed. @tomasborrella thanks again!
