### ISSUE TITLE
[BUG] OutlierRemover is in wrong submodule.

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-lego#335]
`OutlierRemover` should not be in meta. It should be in `preprocessing`. 

![image](https://user-images.githubusercontent.com/1019791/80860371-85a62600-8c67-11ea-9273-2527db1f5110.png)

**Comment by koaning** [comment]
@MBrouns should we put a deprecation warning here while we move it?

**Comment by Abo7atm** [comment]
Hi, does moving the class requires more than moving `outlier_remover.py` to `preprocessing` directory? Also, can I take care of this?

**Comment by MBrouns** [comment]
so it would probably be nicest to copy the class to `preprocessing`, and mark the original class in `meta` with an `@deprecated` decorator as such:

```
@deprecated(
    version="0.4.1",
    reason="Please use `sklego.preprocessing.OutlierRemover instead`",
)
```

Feel free to pick this up!

**Comment by koaning** [comment]
I agree with @MBrouns but I might add the extra text; 

```
@deprecated(
    version="0.4.1",
    reason="Please use `sklego.preprocessing.OutlierRemover instead`. This object will be removed from the meta submodule in version 0.6.0.",
)
```

Just to make it explicit that we intend on removing it later.
