### ISSUE TITLE
[FEATURE] fetch_creditcard

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-lego#351]
It turns out that scikit-learn now has an api for [this service](https://www.openml.org/d/1597). 

We could use it to implement `fetch_creditcard`. For the documentation it'd be amazing to have an outlier detection example. 

@MBrouns any objections? If not I'll go ahead and implement it.

**Comment by MBrouns** [comment]
oh that's really cool! feel free

**Comment by koaning** [comment]
https://github.com/koaning/scikit-lego/pull/352
