### ISSUE TITLE
[FEATURE] "Error Rate Equality Difference" Fairness Metrics

### ISSUE THREAD

**Issue by ogencoglu** [koaning/scikit-lego#357]
_False Negative Equality Difference_ (FNED) and _False Positive Equality Difference_ (FPED) are fairly common fairness metrics for binary classification that are rather easy to implement. Would be nice to have them.

Several academic work use these metrics::

- https://arxiv.org/abs/1808.07231
- https://dl.acm.org/doi/abs/10.1145/3278721.3278729
- https://arxiv.org/abs/1906.08286
- https://arxiv.org/abs/2002.10361
- https://arxiv.org/abs/2005.06625

**Comment by koaning** [comment]
I would agree! 

We're currently considering merging our fairness tools with [fairlearn](https://github.com/fairlearn/fairlearn) though. The idea being that fairness tools deserve their own package and more adult supervision than what we can give with this project. 

While we're exploring this, I'd delay any work on this. But I do certainly agree that our current package is missing some fairness metrics.

**Comment by koaning** [comment]
Closing due to radio silence. Fairlearn is the project for these features going forward.
