### ISSUE TITLE
[DOCS]  Sources format

### ISSUE THREAD

**Issue by david26694** [koaning/scikit-lego#370]
Hi, I think the format of the sources in [Equal Opportunity](https://scikit-lego.readthedocs.io/en/latest/fairness.html#Equal-opportunity) is not completely right. What I see is:
```
<li id="fn1">M. Zafar et al. (2017), Fairness Constraints: Mechanisms for Fair Classification</li>
<li id="fn2">M. Hardt, E. Price and N. Srebro (2016), Equality of Opportunity in Supervised Learning</li>
```
And I guess the `<li id="fn1">` shouldn't be shown.

**Comment by MBrouns** [comment]
Interesting, well spotted! The html tags indeed shouldn't be visible, they were there to have superscript links throughout the notebook but those seem to have disappeared as well

**Comment by koaning** [comment]
@MBrouns This probably happened when we migrated from rst to notebooks.

**Comment by koaning** [comment]
This has since been fixed on our [new docs page](https://scikit-lego.netlify.app/fairness.html).
