### ISSUE TITLE
[FEATURE] pandas log level print

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-lego#371]
This sort of thing can happen currently with out log_level; 

![image](https://user-images.githubusercontent.com/1019791/85380387-2bc22e00-b53d-11ea-86f7-5ebb9208e2c4.png)

If I re-run the matplotlib cell it does go away, but this behavior is a bit annoying. 

Would we have anything against a `print_step` addition to the library?

**Comment by MBrouns** [comment]
this is if you set your log level to debug? I'm not necessarily against print step but maybe this is a documentation issue instead.

```
logging.getLogger('matplotlib').setLevel(logging.INFO)
```

 also solves it

**Comment by koaning** [comment]
This is true, but you'd need to do this for every module that you potentially import. But I agree that two valid PRs can now happen; 

- open to adding `print_step` 
- open to an update to the docs that also explains this phenomenon

**Comment by koaning** [comment]
This got addressed.
