### ISSUE TITLE
[FEATURE] DictMapper

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-lego#372]
![image](https://user-images.githubusercontent.com/1019791/85385682-e4d73700-b542-11ea-8604-6ddd444a048d.png)
In this example you pass the transformer a column to transform but also a dict. In this case you'd pass; 

```
{'young': 1, 'adult': 2, 'old': 3}
```

A transformer that transformers based on a dictionary. I don't know if sklearn has this feature but I couldn't find it.

**Comment by kayhoogland** [comment]
https://github.com/koaning/scikit-lego/pull/375

**Comment by koaning** [comment]
Typically I'd assume that @MBrouns confirms that ideas that I pitch here is a sound one before I start working on an issue and in this particular case I was hoping to use this example in a [calmcode](https://calmcode.io) series. In this case it went fine but @kayhoogland feel free to in the future claim an issue before you start working on it. Otherwise folks might do double work.

That said, I'll gladly have a look at the PR.

**Comment by kayhoogland** [comment]
That makes sense! Next time I will leave a short comment before I start working on it. Since I created this tranformer before, it did not take a lot of time to code.

**Comment by kayhoogland** [comment]
I think this encoder goes beyond the OrdinalEncoder as I can also decide to map a string to a string. For example:

```
{
"Netherlands": "Europe",
"Belgium": "Europe",
"Brazil": "South-America"
}
```

I imagine this can also be GridSearched if I would like to try different mappings. For example:
`{"Amsterdam": "Netherlands", ... }` versus `{"Amsterdam": "Europe", ...}`

**Comment by koaning** [comment]
@kayhoogland this is why I usually wait until @MBrouns gives feedback before I implement something ;). 

From my end: I've tried using the Ordinal Encoder in the past but it is *not* an intuitive API. Note that I think of it, you could also technically use the FunctionTransformer with a lambda to implement this since nothing is really learned here. I do think this approach wouldn't gridsearch nicely because you'd have a lambda function in there.

I can imagine if you map strings to numeric values you could get some gridsearch value out of it though. I like you could enfore monotonicity across a continous variable this way and how you might add the hard "up-down-up" shape too if you'd like. 

```
{"young": 1, "adult": 2, "old": 3}
{"young": 1, "adult": 2, "old": 5}
```

Suppose you'd use these mappings in a disease suseptibility study, I can imagine it can be use-ful to gridsearch.

**Comment by kayhoogland** [comment]
@koaning I learned that the hard way now 😉. 

I agree with your vision and think the DictMapper's flexibility over the OrdinalEncoder can be valuable.
