### ISSUE TITLE
[FEATURE] CumulativeHotEncoder 

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-lego#373]
![image](https://user-images.githubusercontent.com/1019791/85385926-34b5fe00-b543-11ea-992c-7516862dd8c8.png)

It might make sense to have a monotonic encoding for discrete variables.

**Comment by vtoliveira** [comment]
Can you explain more about your idea? Maybe I can help to implement / explore alternatives if you want help.

**Comment by koaning** [comment]
I'd prefer if @MBrouns gives approval first but the idea came from the theme of monotonic models. I'll draw a more expansive example below. 

![image](https://user-images.githubusercontent.com/1019791/86329050-ed67f580-bc45-11ea-89a2-977399edb8b2.png)

Suppose we'd like to encode age into buckets but we'd still like the model to understand that these buckets are monotonic. An example is that we have multiple buckets for age when we're modelling the risk of getting sick from a disease. We'd like to have a model that increases the risk as age increases and we need some way to represent this. 

My theory is that if you were to pass such features to a monotonic regression that you'd get a model with interesting interpretability properties; you'd be able to quantify the extra risk when you move up an age category.

**Comment by MBrouns** [comment]
I think there's a lot of merit to this idea. I've toyed around with something similar for encoding the target of ordered multiclass classification and it seemed to work there, so I expect it to also be useful here.

**Comment by koaning** [comment]
@vtoliveira I'd say this is green for a PR then. Feel free to pick it up.

**Comment by vtoliveira** [comment]
Thanks for the explanation @koaning. I will work on it hopefully to the end of the week. Again, if anyone is interested to discuss / implement it, please go ahead.

**Comment by koaning** [comment]
@vtoliveira There is no rush, but feel free to start working.
