### ISSUE TITLE
[FEATURE] Cyclic features transformer

### ISSUE THREAD

**Issue by david26694** [koaning/scikit-lego#374]
I think it'd be nice to have a transformer for cyclic features. 

It should compute the sine and cosine of the given features divided by their period (times 2 * pi), as in:
![image](https://user-images.githubusercontent.com/22721584/85851384-dd1bca80-b7ae-11ea-817e-c9fb6ce03212.png)

The idea is not new and it is discussed in several places:

- [stackexchange](https://datascience.stackexchange.com/questions/5990/what-is-a-good-way-to-transform-cyclic-ordinal-attributes),
- [Ian London blog](https://ianlondon.github.io/blog/encoding-cyclical-features-24hour-time/),

among others. However, I haven't seen it in scikit-learn.

Ideally, it could handle hours, days in a week, months in a year, day of month, or any cyclical numeric feature. It could also guess the period from the training data if the data is sent in a numeric format. What do you think?

**Comment by koaning** [comment]
Have your seen our RBF repeater?

**Comment by david26694** [comment]
Ok, I thought this needed to create several features which is what bothered me but I see that it's not the case, thanks!
