### ISSUE TITLE
[FEATURE] Add github action with Cron

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-lego#377]
Our project has accumulated a large number of dependencies. This brings downsides on of which is that we might have a broken dependency version. We should add a sniff test for this, probably a daily job that tries to install everything with the latest versions. It seems that we can use [github actions for this](https://jasonet.co/posts/scheduled-actions/) and it might aid in debugging problems like [this one](https://github.com/koaning/scikit-lego/issues/376). Would be good to check if we can run the job on linux/mac/windows.

**Comment by vtoliveira** [comment]
Why not use Travis or Drone for this? (If I understood correctly what you want)

**Comment by koaning** [comment]
We used travis in the past and found that the integration with github can be ... problematic. I've also found it to be slower than github actions. On top of that, travis got sold a while ago and the company that bought it does not seem eager to invest in great service to the unpaying open source projects. 

I appreciate the offer though!

**Comment by vtoliveira** [comment]
Hm, I see your point. I am reading about github-actions so I can help. If you solve this before me, please let me know.

**Comment by koaning** [comment]
If you're interested in taking this one; feel free! Thanks even :)

**Comment by vtoliveira** [comment]
I am! Although it seems pretty much what you said: we just change on for schedule and then do the builds. I am just doing a research to assure that all dependencies will be installed in their latest version through pip. If not, a bash script is appropriate in this case, right?

**Comment by vtoliveira** [comment]
I did some tests, and apparently it installed last version of numba and everything went ok:

https://github.com/vtoliveira/scikit-lego/runs/822892761?check_suite_focus=true

**Comment by koaning** [comment]
That seems like it could work. I might prefer having this check in a seperate file though, just to make sure the workflow for PR/PUSH remains untouched. 

If you create a seperate for it I'm cool with reviewing the PR.

Also, I think once every week might be enough. @MBrouns or do you prefer daily?

**Comment by vtoliveira** [comment]
Hum, yes, it is in a separate file. I just copied the structure and all that I do is pip install scikit-lego, do you think is there anything else to include it?

**Comment by koaning** [comment]
Feel free to make a PR, that way @MBrouns might also have a look. He might have some input on other things that might be useful to add.

**Comment by vtoliveira** [comment]
Created. It is my third time on an open source project. Please any mistake let me know.

**Comment by MBrouns** [comment]
fixed in #378
