### ISSUE TITLE
[FEATURE] A light version that does not depend on cvxpy (and others?) 

### ISSUE THREAD

**Issue by pim-hoeven** [koaning/scikit-lego#380]
Please explain clearly what you'd like to see added. 

- [x] convince us of the use-case, we're open to many suggestions but we prefer to solve problems with pipelines that are at least somewhat general 
**When using the package in a Docker container without C installed, installation (can?) fail on CVXPY**

- [x] ~~add a screenshot if applicable (ML stuff is hard to explain with words, pictures say 1000 words)~~
- [x] ~~make sure that the feature you want is not already supported by sklearn~~

Happy to work on this if you agree

**Comment by koaning** [comment]
@pim-hoeven Is this a feature or a bug that you're reporting?

**Comment by pim-hoeven** [comment]
I think I would go with feature, because it's probably not the most common use. 

It is actually something I encountered a while ago, so not exactly sure. If I remember correctly, it was a very basic docker image without C or Python, after installing Python it was possible to install sklego without dependencies, but not with dependencies. I narrowed it down to cvxpy being the culprit and at that time I opted for just installing without dependencies. 

Currently starting on a new project which will again use sklego, so I thought about this again. Made me wondering whether doing something like `pip install sklego[lightweight]` would be a nicer option. 

I will try to reproduce tomorrow and will keep you posted!

**Comment by pim-hoeven** [comment]
I think the main concern was not that it was not possible to add C to the container, but that we didn't want to include C in the container to be able to install the package. 

> Op 6 jul. 2020 om 22:46 heeft pimhoeven@gmail.com het volgende geschreven:
>

**Comment by MBrouns** [comment]
The problem, in this case, seems to be that `cvxpy` doesn't have wheels available. That might be worth something to fix upstream at some point just to make it easier and faster to install.

That said, I think we could indeed improve some things with regards to the dependencies we install, we currently have a couple of big ones (numba, cvxpy) that are only used for a small subset of the features in the package.

We can tackle this in two axes:

- add extras_require per dependency (e.g. `pip install scikit-lego[cvxpy]`)
- add extras_require per feature group (e.g. `pip install scikit-lego[fairness]`)

Downside of the first is that you require users to know what the dependencies for a module are, downside of the second is that not all fairness stuff needs `cvxpy`. I do think the second one is slightly nicer though.. @koaning?

Would this help you @pim-hoeven?

**Comment by koaning** [comment]
@pim-hoeven one thing I wonder, this problem persists even if you were to install with conda? Part of the solution here does seem to add something about containers and our dependencies to the documentation. Certainly if building a container is tricky we should add an FAQ about it. 

@MBrouns if we were to add this behavior I'd agree that the second method (e.g. `pip install scikit-lego[fairness]`) is certainly preferable. Users will be aware of the submodules of our library but not the dependencies. I've also started noticing while working on fairlearn though that cvxpy is causing a lot of dependency problems. So I wonder if we can make an exception to the rule here by adding something like `pip install scikit-lego[nocvxpy]`.

**Comment by pim-hoeven** [comment]
@MBrouns good call on the wheels and apologies for pointing in the wrong direction. 

I also agree that `pip install scikit-lego[fairness]` would be a nice option. Something else to consider is the pandas way: not adding it to requirements, but checking for and loading the optional dependency. See for example `import_optional_dependency` used [here, line 74](https://github.com/pandas-dev/pandas/blob/v1.0.5/pandas/io/parquet.py#L270-L312) and defined [here](https://github.com/pandas-dev/pandas/blob/v1.0.5/pandas/compat/_optional.py).

@koaning I managed to reproduce the issue, see below. It's quite specific for pip install on a debian image. 

Happy to help out implementing any of the solutions :)

```
07-Jul-2020 12:03:10 | ERROR: Failed building wheel for scs
07-Jul-2020 12:03:10 | Running setup.py clean for scs
07-Jul-2020 12:03:10 | Successfully built umap-learn autograd future wrapt
07-Jul-2020 12:03:10 | Failed to build cvxpy scs
07-Jul-2020 12:03:10 | ERROR: Could not build wheels for cvxpy which use PEP 517 and cannot be installed directly
```

The docker image is based on `debian:stretch` (I don't know why). 

This is the full Dockerfile (I'm sorry it's a bit messy, I don't understand everything in here and don't know what I can omit without having it crash for other reasons)

```
FROM debian:strech

# install utilities
RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive \
    apt-get install --no-install-recommends -y apt-transport-https ca-certificates curl gnupg wget

# install conda (to properly install hdfs3/libhdfs3), the kerberos client and
# the sql server drivers (for pyodbc)
# https://docs.conda.io/projects/conda/en/latest/user-guide/install/rpm-debian.html
RUN wget -q https://repo.anaconda.com/pkgs/misc/gpgkeys/anaconda.asc \
 && echo "deb [arch=amd64] https://repo.anaconda.com/pkgs/misc/debrepo/conda stable main" > /etc/apt/sources.list.d/conda.list \
 && wget -q https://packages.microsoft.com/keys/microsoft.asc \
 && wget -q https://packages.microsoft.com/config/debian/9/prod.list -O /etc/apt/sources.list.d/mssql-release.list \
 && apt-key add anaconda.asc microsoft.asc \
 && rm anaconda.asc microsoft.asc

RUN apt-get update \
 && DEBIAN_FRONTEND=noninteractive ACCEPT_EULA=Y \
    apt-get install --no-install-recommends -y conda

# Install conda
RUN /opt/conda/bin/conda update -n base -c defaults conda \
 && /opt/conda/bin/conda install -y python==3.7.5 \
 && /opt/conda/bin/conda clean -ay

RUN /opt/conda/bin/python -m pip install scikit-lego

CMD pip freeze | grep scikit-lego 
```

Note1: using a python docker image I don't have this issue
Note2: using conda install works fine as well!

**Comment by pim-hoeven** [comment]
Some additional thoughts:

- Not all classes in `linear_model` depend on `cvxpy`, some of them do (`ProbWeightRegression`), some of them don't (`LowessRegression`). How to handle the import of `cvxpy` if we want to use `LowessRegression` but did not install `cvxp`
- I'm not familiar with all other packages, my first thought would be to only exclude `cvxpy` if `[fairness]` is not specified. Another option might be to indeed *exclude* `cvxpy` specifically  using `pip install scikit-lego[nocvxpy]`
- How do you handle versioning? If I include this change, do I upgrade to `0.5.1`?

**Comment by koaning** [comment]
@pim-hoeven what happens if you just use docker with the base python:3.7 image? or the scipy one? those *should* work.

**Comment by koaning** [comment]
If the base python container work as well as conda then I'd argue the docker issue is remedied. It'd still be nice to have an FAQ with a docker example there but it may be good to split this into two seperate issues. 

1. adding a docker example to the docs
2. how to deal with cvxpy-like dependencies (i guess we'll continue that conversation here)

**Comment by pim-hoeven** [comment]
Should have been a it clearer in my previous message, but in base Python:3.7 installing works fine! The specific image that had this issue was debian:stretch (so it might also be the case for other images that do not come with Python installed). 

On the debian image, installing via conda also works!

As I mentioned earlier, this happened around 9 months ago, I think sklego wasn't yet available on conda.

**Comment by koaning** [comment]
@MBrouns to me it feels like cvxpy is the main dependency that is causing trouble. Mayyyybe numba, but mainly cvxpy.

In this situation it seems sensible to have either one of three solutions. 

1. Make the documentation super clear on how to properly install cvxpy. 
2. Make all the cvxpy dependencies optional. Since cvxpy is used in many places in our project I'm not super looking forward to the changes needed to make this work and I also imagine that it will make it somewhat hard to maintain.
3. We can also hard-pin the cvxpy version number such that it just works as we expect. This is slightly less friendly to developers who use cvxpy in their own stack (you can get version conflicts) but it might resolve *most* issues that users have.

**Comment by pim-hoeven** [comment]
Maybe something like this? It is a bit hacky, but does not need a lot of changes
```
try:
    import cvxpy as cp
except ImportError:
    from sklego.utils.uninstalled import UninstalledPackage
    cp = UninstalledPackage("cvxpy")
```
with `sklego.utils.uninstalled` containing

```
class UninstalledPackage:
    def __init__(self, package_name=""):
        self.package_name = package_name

    def __getattr__(self, name):
        raise ValueError(f"The package {self.package_name} is not installed")
```

Then if we call `cp.something()` and `cvxpy` is installed correctly everything works fine. If it isn't installed, every call to `cp.something()` will raise a ValueError (could also be an ImportError or something else). The approach could also be used for multiple packages, if needed.

**Comment by koaning** [comment]
I think the pattern is sensible and it reads as something that I could live with for this package. I only wonder ... is this how other packages also deal with it?

**Comment by pim-hoeven** [comment]
I haven't seen this exact pattern, but I got inspired by [this piece of code](https://github.com/scikit-learn/scikit-learn/blob/c29092d6994a43ea19a82e91c0331e8b7d6e7d36/sklearn/utils/fixes.py#L24) in sklearn:
```
try:
    from pkg_resources import parse_version  # type: ignore
except ImportError:
    # setuptools not installed
    parse_version = LooseVersion  # type: ignore
```

I did not check how this works exactly, but it made me think of using the module name as a class which attributes will raise a nice exception if called in any way.

I'll make a PR :)

**Comment by koaning** [comment]
@pim-hoeven I might wait! I think @MBrouns is on holiday and I just want to make sure he's on board with this.

**Comment by MBrouns** [comment]
I think an `ImportError` would make slightly more sense. I'm fine with the general pattern! It's also how I handle plotting in TimeSeers and it's also how Airflow handles optional dependencies AFAIK. 

Could be that I'm wrong, but I think `pip  install scikit-lego[nocvxpy]` can't actually be defined? I don't think you can remove packages from being installed in `extras_require`, but I'm happy to be shown otherwise

**Comment by koaning** [comment]
@pim-hoeven in that case, you're green for the PR.

**Comment by pim-hoeven** [comment]
This could have been a solution: https://github.com/pypa/setuptools/issues/1139

That would give us a default 'extras' to be installed, which in this case would be cvxpy.

**Comment by koaning** [comment]
Urgh. This is my experience on mac now. 

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-cfe5e76089bc> in <module>
      1 from sklearn.ensemble import RandomForestClassifier
----> 2 from sklego.preprocessing import PatsyTransformer

~/Development/human-learn/venv/lib/python3.7/site-packages/sklego/preprocessing/__init__.py in <module>
     15 ]
     16 
---> 17 from .intervalencoder import IntervalEncoder
     18 from .randomadder import RandomAdder
     19 from .patsytransformer import PatsyTransformer

~/Development/human-learn/venv/lib/python3.7/site-packages/sklego/preprocessing/intervalencoder.py in <module>
      1 import numpy as np
----> 2 import cvxpy as cp
      3 from sklearn.base import BaseEstimator, TransformerMixin
      4 from sklearn.utils import check_array, check_X_y
      5 from sklearn.utils.validation import check_is_fitted

~/Development/human-learn/venv/lib/python3.7/site-packages/cvxpy/__init__.py in <module>
     16 
     17 __version__ = "1.1.5"
---> 18 from cvxpy.atoms import *
     19 from cvxpy.constraints import NonPos, Zero, SOC, PSD
     20 from cvxpy.expressions.expression import Expression

~/Development/human-learn/venv/lib/python3.7/site-packages/cvxpy/atoms/__init__.py in <module>
     18 from cvxpy.atoms.dist_ratio import dist_ratio
     19 from cvxpy.atoms.eye_minus_inv import eye_minus_inv, resolvent
---> 20 from cvxpy.atoms.geo_mean import geo_mean
     21 from cvxpy.atoms.gen_lambda_max import gen_lambda_max
     22 from cvxpy.atoms.gmatmul import gmatmul

~/Development/human-learn/venv/lib/python3.7/site-packages/cvxpy/atoms/geo_mean.py in <module>
     18 import numpy as np
     19 import scipy.sparse as sp
---> 20 from cvxpy.utilities.power_tools import (fracify, decompose, approx_error, lower_bound,
     21                                          over_bound, prettydict)
     22 

~/Development/human-learn/venv/lib/python3.7/site-packages/cvxpy/utilities/power_tools.py in <module>
     16 
     17 from fractions import Fraction
---> 18 from cvxpy.atoms.affine.reshape import reshape
     19 from cvxpy.atoms.affine.vstack import vstack
     20 from cvxpy.constraints.second_order import SOC

~/Development/human-learn/venv/lib/python3.7/site-packages/cvxpy/atoms/affine/reshape.py in <module>
     16 
     17 from cvxpy.expressions.expression import Expression
---> 18 from cvxpy.atoms.affine.hstack import hstack
     19 from cvxpy.atoms.affine.affine_atom import AffAtom
     20 import cvxpy.lin_ops.lin_utils as lu

~/Development/human-learn/venv/lib/python3.7/site-packages/cvxpy/atoms/affine/hstack.py in <module>
     16 
     17 import cvxpy.lin_ops.lin_utils as lu
---> 18 from cvxpy.atoms.affine.affine_atom import AffAtom
     19 import numpy as np
     20 

~/Development/human-learn/venv/lib/python3.7/site-packages/cvxpy/atoms/affine/affine_atom.py in <module>
     20 import cvxpy.lin_ops.lin_utils as lu
     21 from cvxpy.atoms.atom import Atom
---> 22 from cvxpy.cvxcore.python import canonInterface
     23 from cvxpy.expressions.constants import Constant
     24 from cvxpy.utilities import performance_utils as perf

~/Development/human-learn/venv/lib/python3.7/site-packages/cvxpy/cvxcore/python/__init__.py in <module>
      1 # TODO(akshayka): This is a hack; the swig-auto-generated cvxcore.py
      2 # tries to import cvxcore as `from . import _cvxcore`
----> 3 import _cvxcore

ImportError: dlopen(/Users/vincent/Development/human-learn/venv/lib/python3.7/site-packages/_cvxcore.cpython-37m-darwin.so, 2): Library not loaded: @rpath/libc++.1.dylib
  Referenced from: /Users/vincent/Development/human-learn/venv/lib/python3.7/site-packages/_cvxcore.cpython-37m-darwin.so
  Reason: image not found
```

We should really figure out a way to fix this. We might be able to draw inspiration from [how whatlies fixed this](https://github.com/RasaHQ/whatlies/pull/141).
