### ISSUE TITLE
[DOCS] Add F.A.Q. about docker container

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-lego#381]
@pim-hoeven accidentally spent a lot of time getting docker to work with this library. This could have been prevented with an example of a docker file that works. Good reason to add a FAQ.

**Comment by pim-hoeven** [comment]
@koaning should we close this? The conclusion was that my Docker container couldn't build wheels, which has nothing to do with scikit-lego. Also, the default installation does not contain `cvxpy` (which was the culprit in my case).

**Comment by koaning** [comment]
I'm still open to an example of a `Dockerfile` example in our documentation to make it easier for folks to get started. Especially if we also show one with `cvxpy`.
