### ISSUE TITLE
[IMPROVEMENT] Apply lessons of GroupedTransformer to GroupedEstimator

### ISSUE THREAD

**Issue by pim-hoeven** [koaning/scikit-lego#390]
I feel this isn't really a bug nor a feature, so labelled it improvement.

While working on #387 I noticed that grouping can be implemented cleaner and easier if we separate grouping and value data from the start. There is also quite some overlap which I think should be taken away.

In the process we can deprecate `GroupedEstimator` in favour of `GroupedPredictor`

**Comment by koaning** [comment]
I'd start working on it once the transformer is ready but aye, this'd be grand.
