### ISSUE TITLE
Spelling error in sklego.linear_model

### ISSUE THREAD

**Issue by TCACastelijns** [koaning/scikit-lego#391]
https://github.com/koaning/scikit-lego/blob/ffd09a385565ee864bfa884518ac46c6737a97f8/sklego/linear_model.py#L351

While working with the `DemographicParityClassifier` I noticed a spelling mistake in the code as shown above.

The `_DemographicParityClassifer` class should become `_DemographicParityClassifier`

**Comment by koaning** [comment]
Feel free to make a PR.
