### ISSUE TITLE
Smoke test on local machine after `pip install scikit-lego`?

### ISSUE THREAD

**Issue by rickhg12hs** [koaning/scikit-lego#393]
Is there a "smoke test" for scikit-lego after installing with `pip install scikit-lego`?  It'd be nice to know that everything works as intended on a local `pip install`.

**Comment by MBrouns** [comment]
That’s a good question actually. My first idea would be to run the test
suite but it’s not actually included in the package when you pip install.
If the imports work though I don’t really see a reason why it shouldn’t
work. We have tests running daily on the repo.

**Comment by rickhg12hs** [comment]
I'm wondering how easy a `scikit-lego-tests` package might be made that could just execute the test suite.

**Comment by rickhg12hs** [comment]
After installing all the `pytest` dependencies, creating a temporary directory, and `cd`'ing into it, this seemed to work OK to run the test suite on a local `scikit-lego` install.

```
curl -L https://github.com/koaning/scikit-lego/archive/0.5.1.tar.gz | tar -zx scikit-lego-0.5.1/tests --strip-components=1 && pytest tests
```
All the tests seem to pass, though there are plenty of deprecation/future warnings and also a handful of `RuntimeWarning:` and `ConvergenceWarning:`.

My command above is a bit inconvenient in that it is version-number sensitive.

**Comment by MBrouns** [comment]
That might be doable with setuptools. The test suite is already built in a
way that it tests the installed scikit-lego package. I’d welcome a pr if it
doesn’t impact the regular package installation and if you’re willing to
dig into it of course.

**Comment by rickhg12hs** [comment]
I've never created a package before.  I'd hate to put you through my learning curve. :blush:

**Comment by koaning** [comment]
Is smoke testing after an installation common? Is there an example of a package that already does this? I'm a little bit anxious about raising all sorts of errors during the installation process. The idea sounds reasonable, but I'm not sure if it is common practice.

**Comment by rickhg12hs** [comment]
After installation/upgrading from source, smoke testing is very common.  Your project already does this - super!  However, installing packages built and tested on another system require that the package get all the install components, dependencies, machine/OS specifics, etc., exactly right.  Testing after package installation can assure that everything executes as intended on the install machine/OS.  I hope that having the _option_ to smoke test package installs becomes more common.

**Comment by rickhg12hs** [comment]
Updated test from `pip install scikit-lego` automating version number:

```bash
ver=$(python3 -m pip list --format json | jq -r '.[]|select (.name == "scikit-lego")|.version') && \
curl -L https://github.com/koaning/scikit-lego/archive/${ver}.tar.gz | tar -zx scikit-lego-${ver}/tests --strip-components=1 && \
pytest --cache-clear tests
```

**Comment by rickhg12hs** [comment]
After upgrade to version `0.5.2` I'm getting a test error.  I added a print statement which seems to show that `caplog.messages` is empty.

```bash
$ pytest --cache-clear tests/test_pandas_utils/test_pandas_utils.py -k test_logging  -l
Test session starts (platform: linux, Python 3.7.5, pytest 6.0.1, pytest-sugar 0.9.4)
rootdir: /home/rick/tmp/sklego
plugins: sugar-0.9.4, env-0.6.2, mock-3.2.0
collecting ... 

――――――――――――――――――――――――――――――――――――――――――――――――――――― test_logging ―――――――――――――――――――――――――――――――――――――――――――――――――――――

caplog = <_pytest.logging.LogCaptureFixture object at 0x7eff70aa2c10>
test_df =    X1   X2
0   0  NaN
1   1  178
2   2  154

    def test_logging(caplog, test_df):
        caplog.clear()
    
        @log_step
        def do_something(df):
            return df.drop(0)
    
        @log_step
        def do_nothing(df, *args, **kwargs):
            return df
    
        (test_df.pipe(do_nothing).pipe(do_nothing, a="1").pipe(do_something))
    
        print(caplog.messages)
    
>       assert caplog.messages[0].startswith("[do_nothing(df)] n_obs=3 n_col=2 ")
E       IndexError: list index out of range

caplog     = <_pytest.logging.LogCaptureFixture object at 0x7eff70aa2c10>
do_nothing = <function test_logging.<locals>.do_nothing at 0x7eff70b19950>
do_something = <function test_logging.<locals>.do_something at 0x7eff70b19830>
test_df    =    X1   X2
0   0  NaN
1   1  178
2   2  154

tests/test_pandas_utils/test_pandas_utils.py:78: IndexError
------------------------------------------------- Captured stdout call -------------------------------------------------
[]

 tests/test_pandas_utils/test_pandas_utils.py ⨯                                                          100% ██████████
=============================================== short test summary info ================================================
FAILED tests/test_pandas_utils/test_pandas_utils.py::test_logging - IndexError: list index out of range

Results (0.15s):
       1 failed
         - tests/test_pandas_utils/test_pandas_utils.py:63 test_logging
       5 deselected
```

**Comment by koaning** [comment]
Here's the kicker: that failed test was introduced by pytest `6.0.0`. Ever since their latest version their `caplog` seems to work differently. The issue also appeared in scikit-lego v`0.5.1`. They seem to have pushed [an update yesterday](https://pypi.org/project/pytest/#history) but this issue seems more related to pytest than to this library.

**Comment by rickhg12hs** [comment]
Ha!  Yeah I did recently upgrade `pytest`.  Good to know `scikit-lego` is OK.
