### ISSUE TITLE
feature request: grouped model

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-lego#4]
sometimes you'd like to group the dataset into separate parts and run a model in each part. the idea of this model would be that you can add a classified/regressor of your own but this model will make sure it gets run per group. 

note that this model could actually work quite well in combination with a `sklearn.dummy` model.

**Comment by syahdeini** [comment]
I will pick this

**Comment by koaning** [comment]
what is the status of this work? is there a pull request? if not; this is fine but let me know. there may be others who would like to have a go at this model.

**Comment by syahdeini** [comment]
#69 review is needed
