### ISSUE TITLE
[FEATURE] Log shape delta 

### ISSUE THREAD

**Issue by pim-hoeven** [koaning/scikit-lego#407]
Please explain clearly what you'd like to see added. 

I think this is not possible with the `extra` of `log_step_custom` in #397 , but I think it would be a nice feature. 

My current dataframe has shape `(5595919, 9)`, if it loses 100 rows it would be `(5595819, 9)`. I would argue that this is quite easy to miss if we have multiple logs per second (even with colors). Having the delta would result in (-100, 0) for this function, which would stand out if most other logs look like `(0, ...)`. For example, let `read_data` report the actual shape, all intermediate steps report the delta, and the final step report the delta and the final shape, you would get something like:
```
[08/10/20 07:28:32] DEBUG    [read_some_data    ] shape=(5595919, 9),        decorators.py:21
                             time=0:00:30.424626                                             

[08/10/20 07:28:32] DEBUG    [parse_dates       ] shape_delta=(-100, 0),     decorators.py:21
                             time=0:00:00.575011                                             

[08/10/20 07:28:32] DEBUG    [add_features      ] shape_delta=(0, +5),       decorators.py:21
                             time=0:00:01.8340287                                 
            
[08/10/20 07:28:32] DEBUG    [result            ] shape=(5595819, 14),       decorators.py:21
                             time=0:00:30.424626                
```

Another way to overcome this problem is to have a `shape_assertion` decorator on all intermediate steps.

- [x] convince us of the use-case, we're open to many suggestions but we prefer to solve problems with pipelines that are at least somewhat general 
- [x] add a screenshot if applicable (ML stuff is hard to explain with words, pictures say 1000 words)
- [x] make sure that the feature you want is not already supported by sklearn

**Comment by koaning** [comment]
You can do this with the custom logger in that we discuss [here](https://github.com/koaning/scikit-lego/pull/397#issuecomment-670935881). You need to make a stateful function though.

**Comment by koaning** [comment]
Now that I think about it ... I'm actually in favor of perhaps adding `shape_delta` to our standard loggers.

**Comment by pim-hoeven** [comment]
Will add this while working on #397

**Comment by koaning** [comment]
Merged.
