### ISSUE TITLE
[DOCS] Example of using TimeGapSplit

### ISSUE THREAD

**Issue by PyDataBlog** [koaning/scikit-lego#416]
Using this dummy timeseries from pandas. How would I split this data into a training and validation set with a gap of say 1 week?
It is quite unclear from the documentation of the method. 

```py
import pandas as pd

# daily time series
data = pd.util.testing.makeTimeDataFrame(1000, freq='d')
```

**Comment by MBrouns** [comment]
I think this is documented here: https://scikit-lego.readthedocs.io/en/latest/timegapsplit.html
