### ISSUE TITLE
[DOCS] Better Docstring for `make_simpleseries`

### ISSUE THREAD

**Issue by nicoTrombon** [koaning/scikit-lego#422]
- There seems to be a typo or a gramatical mistake in the docsting for `datasets.make_simpleseries` where it says:

> Generate a very simple timeseries dataset to play with. The generator
    **_assumes_** to generate daily data with a season, trend and noise.

I think instead of "The generator assumes to generate [...]" it could say something like "The generator returns a daily time-series with a yearly seasonality, trend, and noise." 
 
I believe it would be clearer. I'd be glad to help out.

**Comment by koaning** [comment]
Fair! Feel free to make a PR.

**Comment by koaning** [comment]
Merged.
