### ISSUE TITLE
[FEATURE] Time Series Grouped Predictor including predictions from last lag

### ISSUE THREAD

**Issue by cmougan** [koaning/scikit-lego#426]
Hi!
I am finding really useful the 'GroupedPredictor' meta estimator. 

I sometimes deal with the a similar problem at work and I have my own sketchy implementation. But after finding of 'GroupedPredictor' I believe that there might be a better way to solve the problem.

I deal with supervised learning time series. Let say I want to predict some feature for the next months [1,12]. What I do that helps is fitting a model per month instead of one generic model. 

What helps, even more, my model is to include in the predictions for month N the predictions that N-1 model made. Example: When I predict March, use the predictions that the month of February has done. 

Also, what I find very helpful is to get the feature relevance for each model. ( This might be a way to get it at the moment)

The feature that I have in mind is adding the predictions of the N-1 group when fitting the N model.

**Comment by MBrouns** [comment]
Hi @cmougan

Apologies for the late reply. It's been busy with the holidays on our doorstep. I think there's merit to your approach, but I think you can get quite far with some of the blocks we already have. Let's make sure we fully understand it first. 

IIUC, you're proposing a transformer that adds the predictions for lagged observations? There are at least two things here:

- Adding predictions as features
- Adding lagged features to other observations

The first of the two should already be possible with the `EstimatorTransformer`. The second point is indeed something that isn't currently in `sklego`, and I think we would be open to having a version of it @koaning? If you want to explore this idea @cmougan I think it'd make most sense to draw out a little design with some expected in- and outputs, and a suggestion for the API. That would make it easier to discuss the exact proposal.

**Comment by cmougan** [comment]
Hi @MBrouns,

I believe that with Estimator Transformer you can get it done. Thanks for letting me know :)

Probably with the Grouped Predictor it could be done in "another elegant way".

Thanks a lot @MBrouns!!
