### ISSUE TITLE
[BUG]  AttributeError: 'GroupedPredictor' object has no attribute 'predict_proba'

### ISSUE THREAD

**Issue by cmougan** [koaning/scikit-lego#433]
I am not sure if it's me that I am not using correctly the API.

When doing a classification problem and using a GroupedPredictor to estimate probabilities I can't get the probabilities

```python
from sklego.meta import GroupedPredictor
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklego.datasets import load_chicken

df = load_chicken(as_frame=True)

# Create a binary target
X = df.drop(columns='weight')
y = np.where(df.weight>df.weight.mean(),1,0)

mod = GroupedPredictor(LogisticRegression(), groups=["diet"])

mod.fit(X,y)

mod.predict_proba(X)
```

`
Traceback (most recent call last):
  File "bug.py", line 25, in <module>
    mod.predict_proba(X)
AttributeError: 'GroupedPredictor' object has no attribute 'predict_proba'
`

**Comment by koaning** [comment]
It might be the case that since our `GroupedPredictor` needs to support both regression and classification that we didn't implement `predict_proba`.

**Comment by koaning** [comment]
Just check the API docs [here](https://scikit-lego.netlify.app/api/meta.html#sklego.meta.GroupedPredictor). Yeah, predict_proba isn't implemented. I'm open to a PR for this feature as long as we make sure we add meaningful error messages when users try to use `predict_proba` on a regression model. 

Also, not every classification model allows for `predict_proba` either.

**Comment by MBrouns** [comment]
`scikit-learn` uses a `@if_delegate_has_method` decorator in these circumstances. (https://scikit-learn.org/stable/modules/generated/sklearn.utils.metaestimators.if_delegate_has_method.html). It raises an `AttributeError` when the method doesn't exist on the base estimator, which seems fine to me

**Comment by cmougan** [comment]
> It might be the case that since our `GroupedPredictor` needs to support both regression and classification that we didn't implement `predict_proba`. Can you confirm that `predict` does work?

I do confirm that in this exact code, if you change mod.predict_proba, by mod. predict you get an output

**Comment by skylarbpayne** [comment]
This can be closed, right?
