### ISSUE TITLE
Least absolute deviation regression & imbalanced regression

### ISSUE THREAD

**Issue by Garve** [koaning/scikit-lego#438]
Hi!

Before I start, great job. This library is great! I want to improve it with the following two ideas.

![reg](https://raw.githubusercontent.com/Garve/scikit-bonus/master/readme_images/special_regressions.png)

Read on for more information.

## LAD Regression
When doing linear regression, we minimize the mean squared error. This makes this approach prone to outliers which is not always wanted. I know that there are some meta estimators like RANSAC and more, but I have not found a simple implementation of a least absolute deviation regression in scikit-learn, which minimized the mean *absolute* error instead of the mean *squared* error. See the left side in the picture above.

Using this, we can even build a regressor that minimizes the [MAPE](https://en.wikipedia.org/wiki/Mean_absolute_percentage_error) (mean average percentage error) when dealing with time series by providing `sample_weight=1/y_train` during fit time. Minimizing the MAPE can be beneficial because especially business people tend to understand this metric better than the r² or MSE.

Therefore, this simple addition has at least two use cases.

I did a small implementation [in my repo](https://github.com/Garve/scikit-bonus/blob/master/skbonus/linear_model/_special_regressors.py) if you would like to take a look. There might be a better way to implement it, but I just used scipy's minimize function and the L-BFGS-B algorithm with a loss and its gradient that I defined by hand.

## ImbalancedRegression
In the same file, there is another linear regressor that punishes overestimations and underestimation done by the model differently, this is the right side of the graphic above. You can specify this by setting a parameter `x` that say 
> Overestimating is x times as bad as underestimating

This changes the loss function of the ordinary LinearRegression by scikit-learn by multiplying each term (y<sub>i</sub>-model(x<sub>i</sub>))² either `x` or 1, depending on if the model(x<sub>i</sub>)>y<sub>i</sub> or not. It behaves kind of like the `sample_weight` parameter during fit time, but it is model output dependent. I also implemented it via scipy's minimize.

Maybe you can use some of these ideas!

Happy to hear from you.

Best
Robert

**Comment by koaning** [comment]
Just to check, are you proposing hosting these models in our repo? It seems they're already hosted on your end so I'm curious to understand if there's a particular reason why you'd want to have hosted in this repository.

**Comment by Garve** [comment]
Heya!

My package is just a small playing ground for getting started, it's not intended to grow much. And I think these functionalities would fit into your package extremely well. 

One reason is because I also want people to be able to use this. Your package has a larger audience already, so there is no reason to open yet another library, I guess.

Best
Robert

**Comment by koaning** [comment]
The implementation looks pretty! There are some minor thoughts in my mind that I might consider before merging it in this repository; 

1. It would be nice if the user can select the optimizer that scikit-learn uses as a hyperparameter. 
2. It would be nice to see if we might also be able to add a regularisation parameter. 
3. It would be nice to think of examples in the documentation. It's one thing to host the method, but this won't have people discover it. 

Other than that I'd say I'm certainly leaning towards hosting this. This might also give me the opportunity to rewrite the slow `DeadZoneRegressor`. One thing; I'm a bit swamped this month so I don't have too much attention to spend on the PR. Just to check @MBrouns how's your availability?

**Comment by Garve** [comment]
Hi!

Happy to hear that :)

1. Sure, can do! I just left it so far, since scikit-learn also doesn't give the possibility and I wanted to keep the signature the same.
2. The question is just if we put it right into the LADRegression, or make different regressors for L1 and L2 regularization, such as LinearRegression/Lasso/Ridge. We can put it all in one place (with some parameters like l1_alpha, l2_alpha), which would yield something like a nave elastic net.
3. I think about it.
4. Very good point!  just checked it, see below. In short: It's on par with the other methods. On these 5 small test, it's never better than RANSAC, for example. But for datasets with many rows and not too many columns, LADRegression is much faster than RANSAC, which might be a selling point. 

![grafik](https://user-images.githubusercontent.com/932327/108190044-b6c9e700-7111-11eb-883d-f1bb217d4b1d.png)
![grafik](https://user-images.githubusercontent.com/932327/108190073-bfbab880-7111-11eb-806c-70bc68ddbba5.png)
![grafik](https://user-images.githubusercontent.com/932327/108190097-c8ab8a00-7111-11eb-88fb-4d6ffa2244dc.png)
![grafik](https://user-images.githubusercontent.com/932327/108190106-cc3f1100-7111-11eb-8349-1453e7ab5074.png)
![grafik](https://user-images.githubusercontent.com/932327/108190122-cf3a0180-7111-11eb-9494-351f2d6eab7e.png)

Best

Robert

**Comment by koaning** [comment]
Do you have any numbers on the speed there? It might be that some random simulation data with a speed benchmark is enough for the docs.

**Comment by Garve** [comment]
Data: 
```python
X = np.random.randn(n, d)
y = np.random.randn(n)
```
With some %%timeit magic:

| LAD  | n=1_000         | n=100_000        |
|------|-----------------|------------------|
| d=5  | 12 ms ± 2.04 ms | 164 ms ± 4.84 ms |
| d=20 | 252 ms ± 35.8   | 1.64 s ± 149 ms  |

| RANSAC | n=1_000           | n=100_000        |
|--------|-------------------|------------------|
| d=5    | 50.1 ms ± 2.62 ms | 259 ms ± 14.5 ms |
| d=20   | 81.4 ms ± 5.85 ms | 522 ms ± 21 ms   |

For larger dimensions, LADRegression seems to be worse. This is probably due to my implementation, though.

**Comment by MBrouns** [comment]
I really like these models as well as your implementation. I'm surprised that RANSAC is faster, although I'd say that your method is still fast enough. I do have some time to look at everything in more detail so that doesn't need to stop us going forward incorporating this.

I think there's some performance gains to be made by replacing the closure in `_get_objective` by simple function or methods and passing the `X`, `y`, and `sample_weight` as `args` through `scipy.minimize` (and perhaps jit those functions as well). 

As a first step for getting this in though we need to make sure everything passes `scikit-learn`s `check_estimator` tests. @Garve how would you like to proceed with this? Are you available for drafting a pull request to get started?

**Comment by Garve** [comment]
Hi!

Thanks :) Sadly, it doesn't pass the check_estimator test yet.

```
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=1e-09
For LADRegression, a zero sample_weight is not equivalent to removing the sample
```

I think it has something to do with the solver precision. Changing it from L-BFGS-B to BFGS helps... sometimes. Still a bit weird, have to look into this.

**Comment by Garve** [comment]
Alright, I changed the solver to SLSQP now and conducted some performance measurement again.

**Summary: using a vanilla RANSACregressor() is often a bit faster, but the scores are always worse.**

|    | Regressor         |   n_samples |   n_features |   Time (seconds, 5 trial average) |   MAD (training set, 5 trial average) |   MAD (test set, 5 trial average) |
|---:|:------------------|------------:|-------------:|----------------------------------:|--------------------------------------:|----------------------------------:|
|  0 | LADRegression()   |        1000 |            1 |                        0.0219872  |                              0.788627 |                          0.69516  |
|  1 | RANSACRegressor() |        1000 |            1 |                        0.00596762 |                              0.80093  |                          0.71082  |
|  2 | LADRegression()   |        1000 |            5 |                        0.0203523  |                              0.762867 |                          0.844674 |
|  3 | RANSACRegressor() |        1000 |            5 |                        0.0340378  |                              0.852647 |                          0.922248 |
|  4 | LADRegression()   |        1000 |           20 |                        0.0371832  |                              0.762677 |                          0.846506 |
|  5 | RANSACRegressor() |        1000 |           20 |                        0.0599632  |                              1.35342  |                          1.37725  |
|  6 | LADRegression()   |        1000 |          100 |                        0.0980177  |                              0.705142 |                          0.8693   |
|  7 | RANSACRegressor() |        1000 |          100 |                        0.333949   |                              2.86044  |                          3.29688  |
|  8 | LADRegression()   |       10000 |            1 |                        0.0127031  |                              0.792998 |                          0.781831 |
|  9 | RANSACRegressor() |       10000 |            1 |                        0.0102597  |                              0.820536 |                          0.811668 |
| 10 | LADRegression()   |       10000 |            5 |                        0.0510426  |                              0.803382 |                          0.78413  |
| 11 | RANSACRegressor() |       10000 |            5 |                        0.0480048  |                              0.934593 |                          0.928367 |
| 12 | LADRegression()   |       10000 |           20 |                        0.0519991  |                              0.795688 |                          0.817111 |
| 13 | RANSACRegressor() |       10000 |           20 |                        0.0759404  |                              1.36884  |                          1.38476  |
| 14 | LADRegression()   |       10000 |          100 |                        0.201913   |                              0.791351 |                          0.793691 |
| 15 | RANSACRegressor() |       10000 |          100 |                        0.441976   |                              2.86152  |                          2.88164  |
| 16 | LADRegression()   |      100000 |            1 |                        0.0814374  |                              0.798216 |                          0.793719 |
| 17 | RANSACRegressor() |      100000 |            1 |                        0.0210882  |                              0.824092 |                          0.818999 |
| 18 | LADRegression()   |      100000 |            5 |                        0.221309   |                              0.79605  |                          0.797408 |
| 19 | RANSACRegressor() |      100000 |            5 |                        0.148595   |                              0.907689 |                          0.91002  |
| 20 | LADRegression()   |      100000 |           20 |                        0.56724    |                              0.799238 |                          0.810259 |
| 21 | RANSACRegressor() |      100000 |           20 |                        0.376579   |                              1.38972  |                          1.39022  |
| 22 | LADRegression()   |      100000 |          100 |                        2.60272    |                              0.798349 |                          0.794871 |
| 23 | RANSACRegressor() |      100000 |          100 |                        1.89237    |                              2.52604  |                          2.53382  |

A fairer comparison is when setting the `max_trials` parameter of the RANSACRegressor to something larger (like 10_000, from 100), so it has the chance to produce better scores. However, then the run time also increases. The result:

|    | Regressor                         |   n_samples |   n_features |   Time (seconds, 5 trial average) |   MAD (training set, 5 trial average) |   MAD (test set, 5 trial average) |
|---:|:----------------------------------|------------:|-------------:|----------------------------------:|--------------------------------------:|----------------------------------:|
|  0 | LADRegression()                   |        1000 |            1 |                        0.0260725  |                              0.788627 |                          0.69516  |
|  1 | RANSACRegressor(max_trials=10000) |        1000 |            1 |                        0.00795851 |                              0.80093  |                          0.71082  |
|  2 | LADRegression()                   |        1000 |            5 |                        0.0221305  |                              0.762867 |                          0.844674 |
|  3 | RANSACRegressor(max_trials=10000) |        1000 |            5 |                        0.147846   |                              0.811642 |                          0.887444 |
|  4 | LADRegression()                   |        1000 |           20 |                        0.0379198  |                              0.762677 |                          0.846506 |
|  5 | RANSACRegressor(max_trials=10000) |        1000 |           20 |                        5.58678    |                              1.01402  |                          1.06349  |
|  6 | LADRegression()                   |        1000 |          100 |                        0.144007   |                              0.705142 |                          0.8693   |
|  7 | RANSACRegressor(max_trials=10000) |        1000 |          100 |                       39.8145     |                              1.68393  |                          1.93953  |
|  8 | LADRegression()                   |       10000 |            1 |                        0.013995   |                              0.792998 |                          0.781831 |
|  9 | RANSACRegressor(max_trials=10000) |       10000 |            1 |                        0.0129669  |                              0.820536 |                          0.811668 |
| 10 | LADRegression()                   |       10000 |            5 |                        0.0670335  |                              0.803382 |                          0.78413  |
| 11 | RANSACRegressor(max_trials=10000) |       10000 |            5 |                        0.286023   |                              0.865635 |                          0.857558 |
| 12 | LADRegression()                   |       10000 |           20 |                        0.065998   |                              0.795688 |                          0.817111 |
| 13 | RANSACRegressor(max_trials=10000) |       10000 |           20 |                        8.34402    |                              0.989098 |                          1.00445  |
| 14 | LADRegression()                   |       10000 |          100 |                        0.229673   |                              0.791351 |                          0.793691 |
| 15 | RANSACRegressor(max_trials=10000) |       10000 |          100 |                       52.038      |                              1.91732  |                          1.91724  |
| 16 | LADRegression()                   |      100000 |            1 |                        0.0819814  |                              0.798216 |                          0.793719 |
| 17 | RANSACRegressor(max_trials=10000) |      100000 |            1 |                        0.0250622  |                              0.824092 |                          0.818999 |
| 18 | LADRegression()                   |      100000 |            5 |                        0.24692    |                              0.79605  |                          0.797408 |
| 19 | RANSACRegressor(max_trials=10000) |      100000 |            5 |                        0.68712    |                              0.849672 |                          0.852322 |
| 20 | LADRegression()                   |      100000 |           20 |                        0.625386   |                              0.799238 |                          0.810259 |
| 21 | RANSACRegressor(max_trials=10000) |      100000 |           20 |                       37.5049     |                              0.9917   |                          1.0006   |
| 22 | LADRegression()                   |      100000 |          100 |                        2.64924    |                              0.798349 |                          0.794871 |
(I canceled the last RANAC run because it took too long. That proves my point.)

Even with more iterations, RANSAC is worse than the LADregressor in terms of scoring performance. But now, the run time is horrible, too, especially with many features.

**Comment by Garve** [comment]
Besides the things from above: Regularization added.
