### ISSUE TITLE
[DOCS] math doesn't render nicely on ImbalancedLinearRegression

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-lego#443]
It's about [this page](https://scikit-lego.netlify.app/api/linear_model.html#sklego.linear_model.ImbalancedLinearRegression). 

![image](https://user-images.githubusercontent.com/1019791/109790360-9ae63b00-7c11-11eb-9156-577275e08615.png)

**Comment by Garve** [comment]
Hi!

I can offer this:

\frac{1}{2 N}\sum\limits_{i=1}^N \mathrm{s}_i \cdot \|y - Xw \|_2^2 + \alpha \cdot l_1 \cdot\|w\|_1 + \frac{\alpha}{2} \cdot (1-l_1)\cdot \|w\|_2^2

![grafik](https://user-images.githubusercontent.com/932327/109803393-464abc00-7c21-11eb-92b8-73ed38e08e4f.png)

**Comment by koaning** [comment]
Feel free to make a PR!
