### ISSUE TITLE
[BUG] Heights of the bumps of the RepeatingBasisFunction

### ISSUE THREAD

**Issue by Garve** [koaning/scikit-lego#447]
Hi!

Not sure if there are good reasons for this, but I noticed the following:

```python
from sklego.preprocessing import RepeatingBasisFunction
import pandas as pd

df = pd.DataFrame({'A': range(100)})

pd.DataFrame(RepeatingBasisFunction(n_periods=50).fit_transform(df)).plot(figsize=(16, 8))
```

outputs 

![image](https://user-images.githubusercontent.com/932327/110220617-0e64a280-7ec7-11eb-8d4f-0c3b83cfe003.png)

i.e. the bumps as lower in the middle. This problem only occurs when I add a lot of bumps on a range that is quite small. Can you confirm this?

Best
Robert

**Comment by koaning** [comment]
I imagine that it's something numeric that's happening. Could you plot this with a higher resolution? Maybe using `np.linspace(0, 100, 1000)`?

**Comment by MBrouns** [comment]
Seems to be an artifact of the high number of periods with the low number of observations indeed, was just trying it.

```python
from sklego.preprocessing import RepeatingBasisFunction
import pandas as pd
import numpy as np

df = pd.DataFrame({'A': np.linspace(0, 100, 1000)})

pd.DataFrame(RepeatingBasisFunction(n_periods=50).fit_transform(df)).plot(figsize=(16, 8))
```

![image](https://user-images.githubusercontent.com/3510863/110235539-d7c37200-7f30-11eb-9586-388709f8c96a.png)

**Comment by koaning** [comment]
I'll close the issue.
