### ISSUE TITLE
[BUG] GroupedPredictor doesn't allow for nans in input

### ISSUE THREAD

**Issue by pavelkrizek** [koaning/scikit-lego#457]
The `GroupedPredictor` raises an error (`ValueError: Input contains NaN, infinity or a value too large for dtype('float64').`) even if the `estimator` can handle missing values itself.

```python
from sklego.meta import GroupedPredictor
import numpy as np
from sklearn.pipeline import make_pipeline
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer
from sklego.datasets import load_chicken

df = load_chicken(as_frame=True)

X, y = df.drop(columns='weight'),  df['weight']
# create missing value
X.loc[0, 'chick'] = np.nan
model =  make_pipeline(SimpleImputer(), LinearRegression())
group_model = GroupedPredictor(model, groups=["diet"])
group_model.fit(X,y)
```

This could be solved i.e. by exposing parameter `force_all_finite` from sklearn function `check_array` into the `GroupedPredictor`

**Comment by koaning** [comment]
Ah! Good find. 

I'm wondering if it instead makes sense to make a flag that ignores the input alltogether. I can imagine that `accept_sparse` might also be "one of those settings" and to prevent an overload of settings, might it work to just allow users to turn off all checking on the grouper end? 

@MBrouns any thoughts from your end?

**Comment by pavelkrizek** [comment]
Thanks for the quick response. I agree I also think that the "ignore all input checks" flag would be a better solution. Probably not losing any safety net because any sklearn `estimator` will check the inputs anyway.
