### ISSUE TITLE
feature request: DebugPipeline

### ISSUE THREAD

**Issue by CorXccelerated** [koaning/scikit-lego#46]
A pipeline that logs extra information before/after every step, which is useful for debugging.

**Comment by MaxHalford** [comment]
This is really interesting. What kind of information are you thinking about?

**Comment by koaning** [comment]
It should be implemented today.

**Comment by CorXccelerated** [comment]
The pipeline is on my fork: https://github.com/CorXccelerated/scikit-lego/tree/debug_pipeline. See the notebook for example usage: https://github.com/CorXccelerated/scikit-lego/blob/debug_pipeline/notebooks/debug_pipeline.ipynb

I will file a merge request after the pipeline is tested.

**Comment by koaning** [comment]
Lookin' good!

**Comment by CorXccelerated** [comment]
Thank you.

I choose to name this pipeline also `Pipeline` . The intention is that it should be easy to replace `from sklearn.pipeline import Pipeline` with `from sklego.pipeline import Pipeline`, and everything should work as is. And now there is the option to add logging with the `log_callback`.

It is up for debate if more clarity is needed enforced by calling this pipeline `DebugPipeline`, but I think this enables easier adoption and `log_callback` signals the programmer something is happening with a log.

**Comment by koaning** [comment]
If you can make a pull request then we can start reviewing. I should mention though that I think I prefer `DebugPipeline`. @MBrouns ?

**Comment by MBrouns** [comment]
There is always the option of `from sklego.pipeline import DebugPipeline as Pipeline` or `from sklego.pipeline import Pipeline as DebugPipeline` so users will always have a choice to do either way

In [imbalanced-learn](https://imbalanced-learn.org/en/stable/auto_examples/pipeline/plot_pipeline_classification.html#sphx-glr-auto-examples-pipeline-plot-pipeline-classification-py) they use `from imblearn.pipeline import make_pipeline`

**Comment by CorXccelerated** [comment]
`make_pipeline` would be a seperate feature request. 

On the same note people could also do `sklego.pipeline import Pipeline as DebugPipeline`.

But I agree with Vincents philosphy that this project is inteded to extent sklearn, not replace.

**Comment by MBrouns** [comment]
Agreed, it was mainly to show that imbalanced-learn just overwrites the name

**Comment by CorXccelerated** [comment]
@koaning If we prefer to not overwrite the `sklearn` names. Do we also want a:

- `DebugFeatureUnion`?
- `make_debug_pipeline`?

I still prefer to keep the sklearn names, because I think it allows for easier use.

**Comment by koaning** [comment]
I like the names that you've supplied. In general though: replacing sklearn names is something that not only doesn't fit the idea behind the package but more-over it can be a cause of confusion.

```
Explicit > Implicit
```

It will take some getting used to though; I definitely agree. But this is something that we might expect . from the user. It is an additional tool, so it is fine that we demand the user spend a little bit of an effort to learn it.

**Comment by koaning** [comment]
I've merged the branch.
