### ISSUE TITLE
[FEATURE] (Linear) Quantile Regression

### ISSUE THREAD

**Issue by Garve** [koaning/scikit-lego#461]
Heya!

At some point, I implemented the LADRegression, which basically minimized sum |y_i - model(X_i)|. This also has the effect that the model over- and underestimates 50% of the time.
As in the ImbalancedRegression, we can also penalize over- and underestimations differently, with some parameter `quantile`. This would have the effect that the model overestimates a share of `quantile` samples and underestimates in `1-quantile` of the cases.

This one would be useful for having some kind of nice confidence intervals around predictions by training a model with `quantile=0.05` and another one with `quantile=0.95`, for example.

I implemented it [here](https://github.com/Garve/scikit-bonus/blob/46c985c6f2c0b371b031977592b23cf0e28c46e3/skbonus/linear_model/_scipy_regressors.py#L301). It's basically a more general LADregression. 

How about we put this into scikit-lego and make the LADRegression just a Quantileregression(quantile=0.5)? Or remove it completely.

Best
Robert

**Comment by koaning** [comment]
I'm certainly open to the idea, but I might prefer to double-check with an example. Do you have a compelling example ready that clearly demonstrates the utility for a QuantileRegressor? 

I'm not super sure I like the idea of immediately deprecating the `LADRegression` since it was added fairly recently. Part of me wants to be pragmatic and say "let's just have both for a while". @MBrouns any thoughts/preferences?

**Comment by koaning** [comment]
One thing to discuss, there are also other libraries that do quantile regression. I just found [this project with a like-able name](https://scikit-garden.github.io/examples/QuantileRegressionForests/).

**Comment by Garve** [comment]
Heya!

A quick demonstration:

```python
from skbonus.linear_model import QuantileRegression
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(123)
X = np.arange(100).reshape(-1, 1)
y = 2*X.ravel() + X.ravel()*np.random.standard_cauchy(100)

q_10 = QuantileRegression(quantile=0.1).fit(X, y)
q_90 = QuantileRegression(quantile=0.9).fit(X, y)
lad = QuantileRegression().fit(X, y)

plt.plot(X, y)
plt.plot(X, lad.predict(X))
plt.fill_between(X.ravel(), q_10.predict(X), q_90.predict(X), alpha=0.33, color='orange')
```

yields

![grafik](https://user-images.githubusercontent.com/932327/116516485-f1988a00-a8cd-11eb-95c3-8acaf53d65ef.png)

So you can have some simple confidence intervals that contain around 80% of the points here.

Regarding scikit-garden:
Yep, it's a great project! But they are doing 100% trees I supposed, the QuantileRegression is just a simple linear classifier.

**Comment by MBrouns** [comment]
I'd say quantile regression is super useful! indeed AFAIK, scikit-garden is focused on tree-based models so having it in this project makes sense. 

I'm okay with having both LADRegression and QuantileRegression around for a while, although we should probably either rewrite LADRegression to use the QuantileRegression, or deprecate the former

**Comment by koaning** [comment]
Grand. @Garve feel free to get started on a PR then. I think the example you show here will work swell for the docs too 👍 

It'd be preferable to have a PR where the `LADRegression` uses the `QuantileRegression` under the hood. Feel free to let me know if there's a good reason to delay that though.
