### ISSUE TITLE
[FEATURE] sample_weights for ZeroInflatedRegressor

### ISSUE THREAD

**Issue by Garve** [koaning/scikit-lego#462]
Hi!

Last time, I tried to use the `ZeroInflatedRegressor` together with your `DecayEstimator`. This resulted in an error because I forgot to implement the `sample_weights` keyword :D

But this should be easy to do, just pass it completely to the classifier as well as parts of it (where the classifier says that the output is non-zero) to the regressor.

Sounds good?

**Comment by koaning** [comment]
Sounds good, just in case though, let's add a unit test to confirm that it works with and without a `sample_weight`.
