### ISSUE TITLE
[BUG] DecayEstimator should be either a classifier or regressor

### ISSUE THREAD

**Issue by Garve** [koaning/scikit-lego#463]
Hi again!

When using the `DecayEstimator` inside the `ZeroInflatedRegressor` an error occurred, because DecayEstimator is neither a regressor nor a classifier.

```python
from sklego.meta import DecayEstimator
from sklearn.base import is_regressor, is_classifier
from sklearn.linear_model import LogisticRegression, LinearRegression

is_regressor(DecayEstimator(LinearRegression())), is_classifier(DecayEstimator(LogisticRegression()))

# (False, False)
```

Maybe the `DecayEstimator` can just mirror the behavior of the estimator we passed in somehow.

**Comment by koaning** [comment]
Ah yeah, interesting one. Technically we only know at runtime if the `DecayEstimator` is a regressor or a classifier. We could try to make the decay estimator both a classifier and a regressor, but I wonder if there are consequences to doing that. 

I don't know if there's a pretty way to attach a mixin to an object at runtime though 😅

**Comment by koaning** [comment]
Maybe a pragmatic observation, when is this an issue in practice? I agree it's an inconsistency, but I wonder when a user would really notice?

**Comment by Garve** [comment]
That's true. I just noticed it when I wanted to put sample weights on the regressor, but not on the classifier.

I'm using it for a time series regression problem for some sales: the regressor should be especially accurate on newer data. The classifier should pick up days (often sundays) where no sales are made, but I wouldn't enforce any sample weights here. But maybe this asymmetric approach is also not good, not sure.

**Comment by vtoliveira** [comment]
I tried to use `DecayEstimator` with `MultiOutputClassifier` and when I fit the model following error shows up:

> AttributeError: 'DecayEstimator' object has no attribute 'classes_'

After investigation for a while, I saw that the check if `self._is_classifier()` is not returning True. Likely due the issue presented here. The model is an `ExtraTreesClassifier`, when I run `[p.__name__ for p in type(decay.model).__bases__]` I get:

 > ['ForestClassifier']
 
 And not any "ClassifierMixin".

**Comment by MBrouns** [comment]
Hm we probably need to implement a classes_ attribute that patches through
to the base estimator, right?

**Comment by vtoliveira** [comment]
Not necessarily, I just used `is_classifier` function from `sklearn.base`, in this way:

```python
def _is_classifier(self):
    return is_classifier(self.model)
```
(Actually, we could use is_classifier function directly rs)

I can send the PR, but it is just a simple adjustment, not sure how to proceed.
