### ISSUE TITLE
[BUG] Tests we do not need

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-lego#473]
@MBrouns I'm wondering. Do we really *need* these tests? 

https://github.com/koaning/scikit-lego/blob/main/tests/test_estimators/test_basics.py

Related, I'm working on a tool that gives insight to pytest runs: https://koaning.github.io/pytest-duration-insights/

**Comment by MBrouns** [comment]
I think these things are covered by the check_estimator checks as well, so
we could probably get rid of them

**Comment by MBrouns** [comment]
Also, that tool looks awesome. What’s the workflow atm?

**Comment by koaning** [comment]
The workflow? 

You need to run this tool that generates the reportlog. After that, the little command-line tool just turns it into a dashboard.
