### ISSUE TITLE
[DOCS] LowessRegression prediction has wrong description? Fit the model using X, y as training data.

### ISSUE THREAD

**Issue by quendee** [koaning/scikit-lego#475]
First comment like should be changed?

```python
    def predict(self, X):
        """
        Fit the model using X, y as training data.

        :param X: array-like, shape=(n_columns, n_samples, ) training data.
        :return: Returns an array of predictions shape=(n_samples,)
        """
```

**Comment by MBrouns** [comment]
Good catch! Feel free to submit a PR if you want

**Comment by quendee** [comment]
@MBrouns Yes ok, I will see if that is the only time that happens or if there are more

**Comment by quendee** [comment]
@koaning I have an encoding that I created sometime ago that might be nice to include.
Do I need to create a detailed issue of what it is?

**Comment by koaning** [comment]
It doesn't need to be super detailed, but yes! feel free to start an issue so we can discuss if your encoding method fits this lib.
