### ISSUE TITLE
Demographic Parity Classifer feature ordering

### ISSUE THREAD

**Issue by joeybodoia** [koaning/scikit-lego#489]
When using the ```DemographicParityClassifer``` with a sensitive column ```z```, are the feature coefficients in the same order as the df columns after dropping the sensitive column?

For example, I'm currently using DemographicParityClassifier on UCI's german credit data, with gender being the sensitive column:

```
dpc_clf = DemographicParityClassifier(sensitive_cols="gender", covariance_threshold=0.013)
dpc_clf.fit(xtrain, ytrain)
```
where xtrain contains 59 features (including sensitive column, gender):
```
In [169]: len(xtrain.columns) 
Out [169]: 59
```
I notice that the the dpc_clf has 58 coefficients:
```
In[170]: len(dpc_clf.coef_[0])
Out [170]: 58
```
I assume that the sensitive feature (gender) does not receive a coefficient, which is why there are only 58 coefficients even though 59 features (xtrain) were originally passed into the model.

Therefore, my assumption is that the coefficients will be in the same order as ``` xtrain.columns.drop('gender')```.
That is, I will correctly assign coefficients to their respective features if I do:
```
dpc_features = xtrain.columns.drop('gender')
coef_dict = {}
for coef, feat in zip(dpc.coef_[0,:],dpc_features):
    coef_dict[feat] = coef

```

I would like to confirm that my assumption is correct.
Please let me know if you have any questions regarding my inquiry, and I'll be happy to clarify.

Thank you in advance!

**Comment by koaning** [comment]
Yep, your assumption sounds correct. If you check the [example in the docs](https://scikit-lego.netlify.app/fairness.html#Experiment) you'll see an alternative code snippet that uses pandas that allows you to compare the coefficients.
