### ISSUE TITLE
sparse data for linear quantile regression yes or no [DOCS] 

### ISSUE THREAD

**Issue by Sandy4321** [koaning/scikit-lego#498]
When something is wrong with the documentation: 

- [ ] please tell us clearly where the mistake is 
may you specify if linear quantile regression works with spares data 
for example
https://scikit-learn.org/stable/auto_examples/linear_model/plot_quantile_regression.html

does not 
- [ ] explain why the mistake is confusing or wrong 
usually scikit methods works with sparse data 
- [ ] suggest a better tone/alternative 
just add comments with linear quantile regression works with sparse data 

It is also perfectly fine to discuss the examples in the documentation here as well.

**Comment by koaning** [comment]
I'm confused. You seem to be discussing an issue with the scikit-**learn** documentation, but you've posted it on the issue board for the scikit-**lego** project. Am I understanding it correctly?

**Comment by Sandy4321** [comment]
yes you understand correctly 

may you specify if linear quantile regression works with spares data?
for example after one hot transforming
then data is only 0s and 1s ?

**Comment by koaning** [comment]
But then ... you would need to ask the scikit-*learn* maintainers since they maintain that tool.

**Comment by MBrouns** [comment]
One-hot encoded data shouldn't be a problem for this regressor, as long as the data gets passed as a normal `ndarray`. `scipy.sparse` matrices won't work out of the box.

This is documented sufficiently in the parameters of the `fit` method:

```
  X : np.ndarray of shape (n_samples, n_features)
            The training data.
```

**Comment by MBrouns** [comment]
https://github.com/koaning/scikit-lego/blob/028597fd0ba9ac387b9faa6f06050a7ee05e6cba/sklego/linear_model.py#L849

**Comment by Sandy4321** [comment]
great thanks
