### ISSUE TITLE
custom optimizer for QuantileRegression  : SLSQP is slow and not performing for one hot data 

### ISSUE THREAD

**Issue by Sandy4321** [koaning/scikit-lego#499]
is it possible to use custom optimizer for QuantileRegression optimizer but not current the SLSQP algorithm
for example to use available in scipy ? 
https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html#scipy.optimize.minimize

since  SLSQP is slow and not performing for one hot data 

https://github.com/koaning/scikit-lego/blob/main/sklego/linear_model.py#L759

**Comment by MBrouns** [comment]
It's not supported in the current code base, though it should technically be possible to make the `method` of the `scipy.minimize` settable as a hyperparameter through the `__init__`. Feel free to make a PR that implements it.

**Comment by GLevV** [comment]
`scipy.optimize.minimize` does not work with sparse data at all. Only transformed from sparse to dense data will give some results.
From my experiments there are differences in results between different optimizer, but it is not huge
