### ISSUE TITLE
feature request: kmeans crossvalidator

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-lego#5]
this is a bit of a silly request, but it is an interesting idea to cross validate on clusters instead of kfolds.

**Comment by koaning** [comment]
The main idea is that you can somewhat safely assume that each cluster (ie. test group) is different from the rest (ie. train group).

**Comment by kayhoogland** [comment]
https://github.com/koaning/scikit-lego/pull/61

**Comment by koaning** [comment]
wasn't this merged?

**Comment by kayhoogland** [comment]
I think I reopened because of the bug in the tests. Can be closed now.
