### ISSUE TITLE
[FEATURE] Categorical Variable Concatenation

### ISSUE THREAD

**Issue by Pacman1984** [koaning/scikit-lego#502]
Concatenating categorical variables is a powerful feature engineering technique, often used in competitions. You could watch the 9 minuts of this Video for understanding the topic: [Winning Solution --> RecSys 2020 Tutorial: Feature Engineering for Recommender Systems](https://youtu.be/uROvhp7cj6Q?t=1704), 

Categorical Variable Concatenation is not implemented in [scikit-learn](https://scikit-learn.org/) or [scikit-learn-contrib](https://github.com/scikit-learn-contrib) packages. 

I have coded this feature in a separate repo [catcomb](https://github.com/Pacman1984/catcomb) and would implement this solution in [scikit-lego](https://github.com/koaning/scikit-lego), if you agree.

Basically, what it does, it concatenates all categorical columns with each other based on some parameters you can chose.

![image](https://user-images.githubusercontent.com/14351072/160833702-6a0db49d-4e62-49e1-bdc4-d01a1c857acc.png)

Its a ColumnsTransformer where you can choose 

- columns: if the categorical columns should be infered automatically, or the column names should be given
- level: the level of 'combinatorial' deepness
![image](https://user-images.githubusercontent.com/14351072/160840018-7209d142-0bd0-4572-9a48-d9f191de5acb.png)

- max_cardinality: the maximal cardinality of the original columns which should be included in the concatenation process, because very high cardinality concatination isn't that useful

Example
`pipe = Pipeline([("catcomb", ColumnsConcatenation(columns='auto', level=2, max_cardinality=500))])`

**Comment by koaning** [comment]
Isn't this numerically equivalent to just using one-hot encoding for each column?

**Comment by MBrouns** [comment]
If I understand correctly, I don't think it's equivalent to one-hot encoding single columns as this would give you an 'AND' on categories (that a linear model for example couldn't otherwise capture). That said, I think a feature like this is better at home in https://contrib.scikit-learn.org/category_encoders/, as that library is focused entirely on dealing with categorical data.

**Comment by Pacman1984** [comment]
The Video attached explains it pretty good with an example, not only linear models also trees and in consequence tree based models like xgboost can not capture the concatination information, because they decise to spit based on the information gain of one feature alone. 

After using the Categorical Combination you also have to apply e.g. a one-hot encoding to use the categorical features in your model.

@MBrouns is maybe right i though about category_encoders or scikit-lego for the contribution.

**Comment by koaning** [comment]
Since the issue moved, I'll close it for now.
