### ISSUE TITLE
ZeroInflatedRegressor with AttributeError

### ISSUE THREAD

**Issue by veeA** [koaning/scikit-lego#519]
Hello,

I was following this tutorial on zero-inflated regression by Dr. Kübler [https://towardsdatascience.com/zero-inflated-regression-c7dfc656d8af](url) and got this attribute error **AttributeError: 'ZeroInflatedRegressor' object has no attribute '_check_n_features'**

This is the line of code which caused it:
`zir.fit(dataset[['Age']], dataset.Salary)`

Thank you.
Vee

**Comment by veeA** [comment]
This is the example I tried, gotten from the website [https://towardsdatascience.com/zero-inflated-regression-c7dfc656d8af](url)

`import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.linear_model import LinearRegression
from sklego.meta import ZeroInflatedRegressor

# Create the salary dataset.
np.random.seed(0)
dataset = pd.DataFrame({'Age': np.random.randint(1, 100, size=200)})
dataset['Salary'] = np.where((dataset.Age > 17) & (dataset.Age < 70), 1500*dataset.Age + 5000 + 10000*np.random.randn(200), 0).round()

# Instantiate the zero-inflated regressor.
zir = ZeroInflatedRegressor(
    classifier=SVC(),
    regressor=LinearRegression()
)

# Easy fit!
zir.fit(dataset[['Age']], dataset.Salary)`

**Comment by koaning** [comment]
I think you miscopied the original code. 

This is what I copied. 

```python 
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.linear_model import LinearRegression
from sklego.meta import ZeroInflatedRegressor

# Create the salary dataset.
np.random.seed(0)
dataset = pd.DataFrame({'Age': np.random.randint(1, 100, size=200)})
dataset['Salary'] = np.where((dataset.Age > 17) & (dataset.Age < 70), 1500*dataset.Age + 5000 + 10000*np.random.randn(200), 0).round()

# Instantiate the zero-inflated regressor.
zir = ZeroInflatedRegressor(
    classifier=SVC(),
    regressor=LinearRegression()
)

# Easy fit!
zir.fit(dataset[['Age']], dataset.Salary)
```

You code has items like `1500dataset.Age + 5000` which is missing the `*` operator.

**Comment by veeA** [comment]
Thank you for your reply.

Even after copying the correct code I still had the same issue.
I ended up reinstalling an older version of scikit-lego and that worked.

**Comment by koaning** [comment]
Could you share the Python versions? If the issue persists in the newer version we'd still be interested in fixing it.

**Comment by veeA** [comment]
I originally installed the newest version (0.6.12) -> that's when I had the error.
Ended up reverting to 0.6.6 and it worked fine.

However I just reinstalled the newest version and it works fine this time. Maybe it's something with dependencies or libraries, I'm not sure.

Thanks for the help again.
