### ISSUE TITLE
[BUG] check_X in GroupedPredictor is incomplete (only used for fit, not for predict/predict_proba)

### ISSUE THREAD

**Issue by skylarbpayne** [koaning/scikit-lego#520]
`GroupedPredictor` offers a `check_X` param which can be used to skip checks if the underlying model you are using can handle missing and/or non-float data. However, this is only used during `fit` and not during `predict` or `predict_proba`.

This means that I can fit a model -- but if I try to predict with data that is missing/not float, it will fail.
This is useful for me, and I imagine others, because we may be using an underlying model which can handle categorical variables encoded as string or handles missing values directly (e.g. as in many GBDT modeling frameworks).

Happy to fix this issue myself -- as without this we can't use this wonderful library 😅 and it seems incredibly straightforward

**Comment by MBrouns** [comment]
Yep, that seems like an omission! A PR would be great!

**Comment by skylarbpayne** [comment]
Thanks @MBrouns -- opened a PR and attached to this issue. I looked through the contributing guidelines but it doesn't seem like there's anything left for me to do -- but let me know if I missed something :)
