### ISSUE TITLE
[FEATURE] Add parameter to allow NaNs in IdentityTransformer

### ISSUE THREAD

**Issue by GLevV** [koaning/scikit-lego#524]
Make parameter `force_all_finite` in `check_array` function available to end user.

**Comment by koaning** [comment]
I'm open to a PR for this, but I'm wondering if we need to check for anything here at all for this component. The `check_array` function checks for many things and I think it might be better to add a single flag for either all the checks or none.

**Comment by GLevV** [comment]
So something like `check_input` bool parameter? And set `True` as default for several releases for backwards compatibility?
