### ISSUE TITLE
[FEATURE] Pass additional parameters to fit underlying estimator in `EstimatorTransformer`

### ISSUE THREAD

**Issue by CarloLepelaars** [koaning/scikit-lego#530]
In `EstimatorTransformer` the underlying estimator is being fitted without the ability to pass along additional arguments to `self.estimator_.fit`. 

This limits use cases for `EstimatorTransformer`. For example, if the underlying estimator is an `XGBClassifier` we would like to be able to pass `eval_set` to monitor validation performance and enable early stopping. This is currently not possible. Adding `*args, **kwargs` should fix this issue. 

https://github.com/koaning/scikit-lego/blob/b4d087f0131ff164e6feebf238356ba6512b3635/sklego/meta/estimator_transformer.py#L31

**Comment by CarloLepelaars** [comment]
@koaning 
> In the future, please don't make a PR until the direction of the solution has been discussed in the issues.
> 
> I'll pick up the conversation there.

Ok, no problem! Will keep that in mind.

**Comment by koaning** [comment]
It's a bit of an sklearn antipattern to pass lots of settings via `.fit()`. Is XGBoost part of sklearn or a 3rd party lib?

**Comment by koaning** [comment]
It's a bit of an sklearn antipattern to pass lots of settings via `.fit()`. Is XGBoost part of sklearn or a 3rd party lib?

**Comment by CarloLepelaars** [comment]
XGBoost is a 3rd party library maintained by [dmlc](https://github.com/dmlc). 

I agree hyperparameters shouldn't be passed via `.fit()`. Unfortunately, some parameters like `eval_set` often can be passed only with `.fit()`. 

Other example use cases are [CatBoost parameters](https://catboost.ai/en/docs/concepts/python-reference_catboost_fit) and [Lightgbm parameters](https://lightgbm.readthedocs.io/en/latest/pythonapi/lightgbm.LGBMRegressor.html#lightgbm.LGBMRegressor.fit) that can only be passed through `.fit()`.

**Comment by koaning** [comment]
I'm a bit uneasy to extend this library beyond scikit-learn because the dependencies quickly start to stack up. @MBrouns what's your opinion on this?

**Comment by MBrouns** [comment]
sklearn does describe the use of `kwargs` in fit methods: https://scikit-learn.org/stable/developers/develop.html#fitting. I'm not sure I like varargs, but I don't see a lot of problems with varkwargs. I would like to see a test added in the PR though before accepting it

**Comment by koaning** [comment]
TIL. 

Yeah so if scikit-learn supports `**kwargs` then I won't mind.

**Comment by CarloLepelaars** [comment]
Sounds great! I removed the `*args` option and added a test.

@koaning Can we reopen [this PR](https://github.com/koaning/scikit-lego/pull/531) or should I create a new one?

**Comment by koaning** [comment]
Either option is fine. Just as long as an issue is discussed before a solution is implemented.

**Comment by koaning** [comment]
Oh! And one more thing. If you're adding this behavior to the estimator transformer, could you also add it to the estimatorpredictor?

**Comment by CarloLepelaars** [comment]
Sure! Will check that out tomorrow. Do you mean pass `**kwargs` through the `.transform` method in `EstimatorTransformer` (+ a test case)?

**Comment by koaning** [comment]
This issue is about the `.fit()` method, no?

**Comment by CarloLepelaars** [comment]
Yes, but what exactly do you mean by estimatorpredictor otherwise? Don't see an `EstimatorPredictor` object in this repository (on the main branch).

**Comment by koaning** [comment]
Ah! Crud. My bad. 

I was confused with the Grouped variant of the meta estimators. These come with a [predictor variant](https://github.com/koaning/scikit-lego/blob/main/sklego/meta/grouped_predictor.py). 

Please ignore the previous comment.

**Comment by CarloLepelaars** [comment]
Aha, thanks for clearing that up! Then I think we are ready for the PR. Will create a fresh one.
