### ISSUE TITLE
GroupTimeSeriesSplit

### ISSUE THREAD

**Issue by sTomerG** [koaning/scikit-lego#537]
**Please explain clearly what you'd like to see added.** 

- To do a KFold cross validation with a time series data set is a bit more complex than other use cases. Folds have to retain chronological order. On top of that it is possible that not every time unit (e.g.) years has the same amount of rows/observations. Therefore, in case of a data set which contains observations over 100 years, it is not feasible to simply split the data set into KFolds with each fold containing the same amount of years, because the first 20 years might contain only 5% of the observations while the last 20% could contain 60% of the observations. 

**add a screenshot if applicable (ML stuff is hard to explain with words, pictures say 1000 words)**
![image](https://user-images.githubusercontent.com/10978711/192142314-25c09771-9919-4af4-8a04-a17e6c8adf79.png)
_If the amount of observations increase over the years, the data should e.g. be split in these folds to have en equal amount of rows/observations per fold._

**make sure that the feature you want is not already supported by sklearn**
- To equally split the data based on the amount of observations, while keeping the chronological order of the time unit is not a KFold method in scikit-learn. scikit-learn's [TimeSeriesSplit](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.TimeSeriesSplit.html#sklearn.model_selection.TimeSeriesSplit) assumes equal group size.

**Comment by koaning** [comment]
This doesn't sound unreasonable. Do you have a name in mind for the component, it sounds like the proposal is to make a variant of `TimeSeriesSplit` that has more flexible settings. 

So, `FlexibleTimeSeriesSplit` 😅 ? @MBrouns do you have other suggestions? 

It might also be good to discuss which settings we'd like to add because I'm wonder if we can come up with other features besides just the size of groups. It'd be good to think about that upfront instead of patching that later.

**Comment by koaning** [comment]
Ah. Only now do I see the name of the issue. Does the component you have in mind offer behavior that's very different from the `TimeSeriesSplit`? If not, it might be nice only to modify the name slightly.

**Comment by MBrouns** [comment]
I think the implementation is most succinctly described as "GroupKFold" with strictly monotonically increasing group_ids in folds. The most common use case would be time series though, so maybe `GroupTimeSeriesSplit`?

**Comment by GLevV** [comment]
It's a time series splitter. In sklearn timeseriessplit is cumulative, this one is windowed. You can see implementation of both, for example [here](https://github.com/alan-turing-institute/sktime/blob/main/sktime/forecasting/model_selection/_split.py)

**Comment by sTomerG** [comment]
> It's a time series splitter. In sklearn timeseriessplit is cumulative (expanding window), this one is sliding window. You can see the implementation of both, for example [here](https://github.com/alan-turing-institute/sktime/blob/main/sktime/forecasting/model_selection/_split.py)

Thanks for the suggestion. I'm not sure if these from sktime calculate themselves the optimal split points given `n_splits` to create as equally sized folds as possible when the amount of rows/observations per time unit is different (see image in feature request). I've finished the code for the `GroupTimeSeriesSplit`, I'll compare its output with those of sktime to see if it's actually doing the same thing or not.

**Comment by sTomerG** [comment]
> > It's a time series splitter. In sklearn timeseriessplit is cumulative (expanding window), this one is sliding window. You can see the implementation of both, for example [here](https://github.com/alan-turing-institute/sktime/blob/main/sktime/forecasting/model_selection/_split.py)
> 
> Thanks for the suggestion. I'm not sure if these from sktime calculate themselves the optimal split points given `n_splits` to create as equally sized folds as possible when the amount of rows/observations per time unit is different (see image in feature request). I've finished the code for the `GroupTimeSeriesSplit`, I'll compare its output with those of sktime to see if it's actually doing the same thing or not.

The splitters of sktime don't calculate themselves the optimal split points for as evenly divided folds as possible, with just `n_splits` as input. Therefore I believe this `GroupTimeSeriesSplit` (or however we want to call it) is indeed a new feature.
