### ISSUE TITLE
Remove Deprecated Code

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-lego#538]
Over the years some deprecated code was introduced, for the 0.7.0 release underway it should finally be removed. 

Here are some of the examples that I found 

- [x] [sklego.meta.outlier_remover](https://github.com/koaning/scikit-lego/blob/main/sklego/meta/outlier_remover.py#L12-L17)
- [x] [sklego.linear_model](https://github.com/koaning/scikit-lego/blob/main/sklego/linear_model.py#L367-L373) this is about the FairClassifier
- [x] [sklego.meta.grouped_estimator](https://github.com/koaning/scikit-lego/blob/main/sklego/meta/grouped_estimator.py#L5-L9)

**Comment by koaning** [comment]
Technically, I think after this change the `deprecated` module isn't needed anymore. Any objections is this dependency is also removed @MBrouns or are there new deprecations coming in?

**Comment by MBrouns** [comment]
You never know, but overall I think we managed to keep deprecations low. Might as well remove it as a dependency in the meantime

**Comment by koaning** [comment]
I'm aware of the removal, I was [somewhat involved](https://koaning.io/posts/just-another-dangerous-situation/).

Maybe we can add the dataset to our datasets module, with a docstring that gives appropriate context?

**Comment by koaning** [comment]
This might also be of interest: https://fairlearn.org/main/user_guide/datasets/boston_housing_data.html

**Comment by FBruzzesi** [comment]
Fixed in #626
