### ISSUE TITLE
Large Volumes of Tests Failing in Local PyTest Run

### ISSUE THREAD

**Issue by john-hawkins** [koaning/scikit-lego#546]
Good morning,

I have forked the project to prepare some modifications to contribute.

I am trying to run the test suite before adding my own tests and I am finding that large numbers of the tests fail on my local machine. I checked the setup.py to confirm that my local machine had the right dependencies and I cannot see anything that should cause a problem.

1. Is there something I need to do in order to have my local setup run the tests?
2. Is local testing the correct approach? Or should I just enable the GitHub workflows in the forked repository?

-----------------------
...
ERROR tests/test_meta/test_subjective_classifier.py::test_predict_proba[both-expected_probas2]
ERROR tests/test_preprocessing/test_outlier_remover.py::test_no_outliers
ERROR tests/test_preprocessing/test_outlier_remover.py::test_remove_outlier
ERROR tests/test_preprocessing/test_outlier_remover.py::test_do_not_refit
============ 161 failed, 3075 passed, 442 warnings, 17 errors in 107.93s (0:01:47) ============

**Comment by koaning** [comment]
It would help if you could share some more information. What operating system and Python version are you using? 

Technically, it could be that you've installed a recent version of scikit-learn, could you share that version as well?

**Comment by koaning** [comment]
It does seem like your errors are similar to the ones that failed in [our cronjob](https://github.com/koaning/scikit-lego/actions/runs/3317175027/jobs/5479752076), indicating this is likely a "new version of sklearn introduced a minor but breaking bug" kind of a thing.

**Comment by john-hawkins** [comment]
Thanks @koaning 

Running on a Mac laptop
ProductVersion:	11.3.1
BuildVersion:	        20E241

% python --version
Python 3.9.15

% pip freeze | grep scikit-learn
scikit-learn==1.0.2

**Comment by koaning** [comment]
I tried reproducing it locally, but didn't find the same issues. Just to check ... are you running on an M1 Mac?

**Comment by MBrouns** [comment]
Could you post the pytest output to pasteboard or something similar?

**Comment by john-hawkins** [comment]
@koaning -- It is an Intel Mac. 
I am going to try with some setup variations.

@MBrouns -- Will do

**Comment by john-hawkins** [comment]
My apologies everyone.

I have resolved the issue myself.

It was related to not having the all testing packages installed correctly.
