### ISSUE TITLE
[FEATURE] Adding the MRMR (Maximum Relevance Minimum Redundancy) feature selection

### ISSUE THREAD

**Issue by Garve** [koaning/scikit-lego#553]
Hi!

The only feature selections that scikit-learn offers are quite naive. MRMR seems like a bit more advanced and reasonable approach to select informative and non-redundant features as described [here](https://medium.com/towards-data-science/mrmr-explained-exactly-how-you-wished-someone-explained-to-you-9cf4ed27458b).

Long story short: 
1. Pick a feature that is most informative in some metric (e.g. F-statistic).
2. Pick the next feature that is very informative, but doesn't correlate with the previous feature too much (e.g. the average absolute Pearson correlation between the current feature and the feature selected in step 2).
3. Pick the next feature that is very informative, but doesn't correlate with the previous 2 features too much.
4. Pick the next feature that is very informative, but doesn't correlate with the previous 3 features too much.
5. (repeat until _K_ features selected)

Here, _K_, the measure of information and correlation can be specified by the user.

**Comment by koaning** [comment]
Doesn't the link that you provide also mention an existing Python package that already implements this behavior? If so, does it really need to appear in two packages?

**Comment by Garve** [comment]
Ah the package looks more like a prototype, it's just a simple function. It's not pretty, but the main drawback is that it's not scikit-learn compatible.

I thought more of something that you find in the feature_selection subpackage of scikit-learn, such as the VarianceThresholder, SelectKBest, ...

**Comment by Garve** [comment]
That's the original implementation by the author of the TDS article: https://github.com/smazzanti/mrmr/blob/main/mrmr/main.py

However, I see it as more educational.

**Comment by koaning** [comment]
I see. In that case, I'm open certainly to the idea, but it'd help if there's a compelling example for the docs. One example that shows the merits of the approach compared to other methods.

**Comment by Garve** [comment]
I can ask the author if it's ok for him to use one of his. He also wrote [a nice article](https://towardsdatascience.com/feature-selection-how-to-throw-away-95-of-your-data-and-get-95-accuracy-ad41ca016877) about the MNIST dataset, and that it's possible to only use 5% of the pixels to get a 95% test accuracy.

## Long story short
Here are the top pixels (features) according to some famous algorithms:
![image](https://user-images.githubusercontent.com/932327/208925257-4d775c62-9d9b-4b4c-a841-3392f020d908.png)
(Image by Samuele Mazzanti, the author)

The darker pixels are more important than the lighter ones. Here, you can see how for all methods but MRMR the most important pixels are clustered together, although maybe only a single pixel from these clusters would suffice already, as it captures enough information about this area. In the MRMR image, you can see that the first important pixels are more widespread, covering a wider area. While I think that this is nice already, the author also created a comparison in terms of accuracy.

![image](https://user-images.githubusercontent.com/932327/208926103-933a71ac-86a8-4fbb-8d58-55c859af93b4.png)
(Image by Samuele Mazzanti, the author)

**Comment by koaning** [comment]
If the tutorial can be passed along I think I'm open to it. 

Just to check, @MBrouns any concerns?

**Comment by MBrouns** [comment]
No concerns here!

**Comment by fabioscantamburlo** [comment]
Hello! 
Are you still interested in having this feature? 
I may give it a try to implemented it.👨🏼‍💻

**Comment by Garve** [comment]
Heya? I definitely am 😄

**Comment by FBruzzesi** [comment]
Closed by #622, will be added in the next release
