### ISSUE TITLE
[BUG] Github Actions fail because boston housing was removed from scikit-learn 

### ISSUE THREAD

**Issue by Garve** [koaning/scikit-lego#555]
Hi!

Just created a PR and noticed that. Seems that we have to change the testing dataset or download it manually.

Best
Robert

**Comment by koaning** [comment]
Ah, yeah. This was found to happen. 

The dataset is still hosted and fetch-able via the [fetch_openml](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.fetch_openml.html) function. Thanks for reporting!
