### ISSUE TITLE
[SUGGESTION] New Version Release

### ISSUE THREAD

**Issue by KulikDM** [koaning/scikit-lego#564]
Hi, thanks for accepting my [PR 562](https://github.com/koaning/scikit-lego/pull/562) recently. It seems that it was with good foresight as `scikit-learn` released version 1.3.0 yesterday with that previous decorator now being depreciated and removed. However, while the update is integrated in the repo, the PyPi and Conda packages are still vulnerable. Perhaps a new release?

**Comment by koaning** [comment]
Hi there. Sorry for the delay. Life with a baby gets in the way sometimes. 

I'll make a quick release right now for pypi, hopefully the conda-forge repo picks it up quickly after.

**Comment by koaning** [comment]
Mhm. There seems to be something breaking. Can't make a super quick patch now. Will have to look into this later.

**Comment by KulikDM** [comment]
@koaning I can only imagine, sterkte, and thank you for getting back ;) 

The issue seems to be from a [fix](https://github.com/scikit-learn/scikit-learn/pull/26325) make in `sklearn = 1.0.3` where [pipeline.Pipeline.fit_transform](https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.Pipeline.html#sklearn.pipeline.Pipeline.fit_transform) now raises an AttributeError if the last step of the pipeline does not support fit_transform. Not sure how this can be fixed, but [here are the changes made in sklearn](https://github.com/scikit-learn/scikit-learn/pull/26325/files/2944155f8c88b155d296147878f9ef9e1f8d9a15).

All the best! And will try help if I can.

**Comment by koaning** [comment]
Ah wait. Then the fix is relatively simple. I just have to update the object that's used in testing. Will figure out some time to have another look!

**Comment by KulikDM** [comment]
Hi @koaning, I've found a quick fix that can help get the tests to pass. If you add 
`IGNORE_TESTS = ("test_set_pipeline_step_passthrough", "test_pipeline_raise_set_params_error",
                "test_set_pipeline_steps")`  <--
to the `test_debug_pipeline_w_sklearn_test.py` file.

Hope this is a valid temporary/permanent solution.

**Comment by koaning** [comment]
@MBrouns at this point I'm actually fine with the aforementioned solution. It's not ideal, but neither is endless waiting for a patch release. Any concerns if I turn off those tests with an XFAIL?

**Comment by KulikDM** [comment]
Hi @koaning, to clarify it's just this `test_set_pipeline_steps` test, the other two skipped steps already exist in the testing script.
