### ISSUE TITLE
[DOCS] Model Selection API Rendering

### ISSUE THREAD

**Issue by FBruzzesi** [koaning/scikit-lego#568]
While going through the time series cross validation classes I noticed that rendering is somehow broken:

- `GroupTimeSeriesSplit`[^1]: 
  - The example doesn't render properly as a table
  - The example is after the param specification (not sure if that is intended)
- `TimeGapSplit`:
  - The first list is rendered in line (_The splits are made based on ..._) [^2]
  - The second list is rendered in line and the second equation possibly misses a "*" operator
  - The params and return types do not render properly in the `split `and `summary` methods [^3]

Happy to open a PR to fix such API page rendering.

[^1]: ![groupedtimeseries-screenshot](https://github.com/koaning/scikit-lego/assets/42817048/f1b73b72-7d26-4086-94a4-d925c064dd40)

[^2]: ![timegapsplit-screenshot](https://github.com/koaning/scikit-lego/assets/42817048/be02b9fa-2f40-4679-adfd-12e352238ea2)

[^3]: ![methods-screenshot](https://github.com/koaning/scikit-lego/assets/42817048/152155f3-881b-4f25-a701-97ff0fb8ef02)

**Comment by koaning** [comment]
Feel free to make a submission. Make sure you try and render it locally first though. It's possible that we may simply need to push again because our doc deployments aren't automated.
