### ISSUE TITLE
[BUG] `DeadZoneRegressor` with "constant" effect

### ISSUE THREAD

**Issue by FBruzzesi** [koaning/scikit-lego#587]
# Description

[`DeadZoneRegressor`](https://github.com/koaning/scikit-lego/blob/main/sklego/linear_model.py#L135) allows for the parameter `effect="constant"`. However such case is not managed in the [`deadzone` function](https://github.com/koaning/scikit-lego/blob/main/sklego/linear_model.py#L169C13-L169C21), which leads to return a value `None` and breaking the API rightafter.

I am not sure what the expected behaviour is. My guess would be something like:

```py
if self.effect == "constant":
    return np.where(errors > self.threshold, some_constant_value, np.zeros(errors.shape))
```
However such `some_constant_value` is nowhere defined.

# Code to reproduce

```py
from sklego.linear_model import DeadZoneRegressor
from sklego.datasets import load_chicken

X, y = load_chicken(return_X_y=True)
model = DeadZoneRegressor(effect="constant")

_ = model.fit(X, y)
```

> TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'

# Unit test to catch the bug

It should be enough to add `"constant"` to the list of parameter in the [fixture](https://github.com/koaning/scikit-lego/blob/main/tests/test_estimators/test_deadzone.py#L17)

**Comment by koaning** [comment]
That indeed feels like an omission. Feel free to make the PR. 

One thing: I wonder if this component is used much. One downside of the implementation is that it's pretty darn slow.

**Comment by FBruzzesi** [comment]
> However such `some_constant_value` is nowhere defined.

Doesn't matter the value, right? Can just use 1, it just a matter of scale.

> One downside of the implementation is that it's pretty darn slow.

Any big reason not to move to [scipy.optimize.minimize](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html)?
I understand the original intent was to track all loss values, weights and gradients.

**Comment by koaning** [comment]
> Doesn't matter the value, right? Can just use 1, it just a matter of scale.

Yep! 

> Any big reason not to move to [scipy.optimize.minimize](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.minimize.html)?

I'm certainly open to it. If it works out it would be nice to drop a dependency. 

> For sure the effect="constant" was not used 😂

Yep! 😅
