### ISSUE TITLE
`HierarchicalPredictor` and `HierarchicalTransformer`

### ISSUE THREAD

**Issue by FBruzzesi** [koaning/scikit-lego#620]
# Description

As noted in #616 and discussed on private channels, `GroupedPredictor` class has its shortcomings.

I am opening this issue to keep track on how we could expand from what we learned.
Here a list of features that `HierarchicalPredictor` and `HierarchicalTransformer` should have in my opinion:

1. Given an input group, all levels should be fitted, including a global model
    - Example: `groups = ["a", "b"]`, groups to fit are: `["global"], ["global", "a"], ["global", "a", "b"]`
    - This implies that now the order _always_ matters, not only when shrinkage is not None.
    - This is quite opinionated, but also guarantees that 3.1 (see later) always works.
2. Shrinkage available for **both** regression and classification tasks (tbd how it could be extended to outlier detection)
3. Fallback strategy to be either `"next"` or `"raise"`, meaning:
    - `"next"`: if a group value is not found at prediction/transformation time, it fallbacks to the first available group in the hierarchy.
    - `"raise"`: if a group value is not found at prediction/transformation time, an error is raised.
    - ~Disclaimer: better value instead of "next" can be found 😂~ what about `"parent"`?
4. Allows for extra params in fit (e.g. `sample_weight`), which is currently not possible.

A first draft of the implementation was developed in #618, however trying to keep the current behavior of `GroupedPredictor` as well as expanding its functionalities was going to become a headache both to develop and maintain. This is why an implementation from scratch would make sense.

## Edit

A few considerations regarding the hypothetical `HierarchicalTransformer`:

- Shrinkage doesn't really make sense, or at least not for all transformers. In fact the current `GroupedTransformer` doesn't support it.
- Should the group columns be returned as they are from the `.transform(X)` operation?
- Should the `.transform(X)` output maintain the input type? Hence if pandas dataframe maintain the index  as well?

**Comment by koaning** [comment]
> Shrinkage doesn't really make sense, or at least not for all transformers. In fact the current GroupedTransformer doesn't support it.

Agree! 

> Should the group columns be returned as they are from the .transform(X) operation?

It feels like it would be fine to default to not returning the group columns. Mainly because users could select them seperately in the pipeline if they were so inclined. Might make for a good parameter though.

> Should the .transform(X) output maintain the input type? Hence if pandas dataframe maintain the index as well?

I would prefer not to rely on anything pandas specific with the advent of possible polars support. Is there a use-case you had in mind where that's required?

**Comment by FBruzzesi** [comment]
Ok, these will definitely be (at least) two separate PRs, one for predictor and one for transformer (the predictor one could land late this week 😁)

> Might make for a good parameter though

"passthrough" vs "drop" seems suitable

> Is there a use-case you had in mind where that's required?

Absolutely not, I started to rely on indexes as less as possible, but since pandas and polars input/output are supported by scikit-learn, I am wondering what is the behavior one should expect.

**Comment by AhmedThahir** [comment]
Will sample_weight be on the roadmap?

**Comment by FBruzzesi** [comment]
@AhmedThahir thanks for reaching out!

> Will sample_weight be on the roadmap?

Not really a roadmap, but definitly in scope. Let us know if you would like to try to set this up, otherwise I will take a look during the weekend  🙌🏼

**Comment by AhmedThahir** [comment]
Would like to try to implement it. If it doesn't work, you may go ahead with it.

Quick Logic
- Pass an array of sample weights with same length as y
- These will be grouped along with X and y
- When passing to fit, they will be unpacked to the individual fits

Will share for review once done.
