### ISSUE TITLE
[DOCS] Document KlusterFoldValidation

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-lego#630]
Related to https://www.linkedin.com/feed/update/urn:li:activity:7176859386554789888?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A7176859386554789888%2C7176877653679894528%29&dashCommentUrn=urn%3Ali%3Afsd_comment%3A%287176877653679894528%2Curn%3Ali%3Aactivity%3A7176859386554789888%29

It doesn't help that it is misspelled but the docs are also just plain missing. No bueno. Will pick this up during the pyladies sprint tomorrow.

**Comment by FBruzzesi** [comment]
Regarding the name: is there a (historical) reason for which it is spelled `Kluster`? We can always change it to `ClusterFoldValidation` to re-brand it and deprecate the other for a few versions.

I don't have some data/use case for which write some docs about it, but looking forward to that 👌

Thinking about the docs: for someone completely new to the project, the fact that code and markdown are so separated may not be intuitive and some explanation could help. I will try to add it in the `contribution` section soon

**Comment by koaning** [comment]
I'm certainly open to deprecating the old one, I don't think people were even really using it. 

Out of curiosity, do you remember why you split up the code and markdown when you redid the docs?
