### ISSUE TITLE
[DOCS] Remove netlify docs

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-lego#632]
Folks google and still find the old docs. @koaning should add a redirect.

**Comment by FBruzzesi** [comment]
I thought that one was removed, just figured it still exists and appear on top of google search 🙈

**Comment by koaning** [comment]
Netlify didn't do the redirect that I wanted so instead I did this hacky beauty on the site:

```
<script>
window.open("https://koaning.github.io/scikit-lego/","_self")
</script>
```

Seems to work for humans.
