### ISSUE TITLE
[DOCS] Missing explanation on how to  run the documentation locally

### ISSUE THREAD

**Issue by likeajumprope** [koaning/scikit-lego#637]
When something is wrong with the documentation: 

The contributing guidelines under https://koaning.github.io/scikit-lego/contribution/ do currently not include how to run the documentation locally for development.

**Comment by FBruzzesi** [comment]
Thanks for reporting!
I had this planned for a bit and only added it as a [readme](https://github.com/koaning/scikit-lego/blob/main/docs/README.md) but always postponed to properly integrate it! 
Will work on a dedication section for how to write and test documentation.
