### ISSUE TITLE
`decomposition.umap_reconstruction.UMAPOutlierDetection`

### ISSUE THREAD

**Issue by FBruzzesi** [koaning/scikit-lego#653]

**Comment by FBruzzesi** [comment]
@anopsy created separate issues to link directly PRs

**Comment by anopsy** [comment]
Thanks! I'll also repeat my question:

**what would be a more elegant example - applying them on ndrrays or a dataframe?**

I noticed that some examples in sklego are based on dataframes and some on numpy arrays or ndarrays. I noticed that scikit-learn mostly uses arrays in their examples. Let me know what do you think, maybe I'm overthinking that

**Comment by FBruzzesi** [comment]
I would suggest to use arrays as well wherever possible. Dataframes may be more interpretable but they are more in the direction of skrub philosophy

**Comment by anopsy** [comment]
Coolio! That's more of an idea for the future, but when all examples are added, maybe it would be good to base them all on arrays then. Just sayin'

**Comment by FBruzzesi** [comment]
Closed by #654
