### ISSUE TITLE
[FEATURE] Feature capping

### ISSUE THREAD

**Issue by stephanecollot** [koaning/scikit-lego#66]
Use case:

In ML some time your features have extreme large values or even infinite value (np.inf), we want to cap those values with a feature transformer.

Parameters:
- feature to cap (and/or feature to no cap?)
- min value
- max value

**Comment by koaning** [comment]
I like the sound of this transformer. It sounds simple enough too. 

1. I wonder about features not to cap though. Probably only a few columns need tweaking. This is my guess.
2. Instead of setting a min/max level per column, might it make sense to cap everything at a certain quantile (this is something that you might more easily do against all columns).

**Comment by arthurpaulino** [comment]
Capping can be a dangerous move for `np.inf` cells. `pandas` dataframes interprets divisions by 0 as `np.inf` or `-np.inf`, depending on the signal of the numerator:
```python
>>> import pandas as pd
>>> df = pd.DataFrame({'numer':[1, -1], 'denom':[0, 0]})
>>> df['div'] = df['numer']/df['denom']
>>> df
   numer  denom  div
0      1      0  inf
1     -1      0 -inf
```
When, in fact, divisions by 0 make no sense and could very much be either `np.inf` or `-np.inf` or anything else (undetermined).

Such ±inf cells are common results of feature engineering processes (e.g.: dividing the loan amount by the income). I usually replace them by `np.nan` and then deal with those from there.

I know that, for instance, [LightGBM](https://lightgbm.readthedocs.io/en/latest/index.html) is capable of dealing with nan cells. And it does it in a way that every attempt of mine to input values on nan cells ends up with lower accuracy. So I just leave it to LightGBM these days. I wonder how it does it, though. What do you guys think?

**Comment by koaning** [comment]
The idea here (and feel free to discuss it) is to allow the user to tell the model "you know what ... for my model, if you're older than 70 ... you might as well be 70". the idea here being that depending on the spread in the dataset this might reduce it. The user needs to have a good reason to do so but this is therefore also the users responsibility. 

It might make sense that the "cap" can also be specified manually.

**Comment by koaning** [comment]
Note that such a transformer needs to work on a pandas dataframe as well as the numpy array.

**Comment by arthurpaulino** [comment]
Interesting idea. What if the user had a way to ask the model about the impact of capping beforehand? Or even better, a capping report, so to speak, which would help the user to choose safe capping thresholds.

This idea of "asking the model beforehand" opens space for a lot of interesting features that I don't see on other libs. But I'll stick to the capping idea on this issue.

About ignoring `np.inf`, it makes sense to me on tree-base models. But what about algebraic models like linear regressions? Do you mean ignoring the row entirely? What about `np.inf` cells on the testing dataset?

**Comment by koaning** [comment]
Want to have a go at an implementation? 

Note that there are some tricks. If you remove all the `NaNs` and `Infs` and `Na` and junk ... then you might say cap everything beyond the 5th/95th quantile. One might consider doing all of this before passing it along to a `StandardScaler`. This ColumnCapper could then take all `inf` values and cast them to the 95th percentile and `-ing` to the 5th.

**Comment by arthurpaulino** [comment]
> Want to have a go at an implementation?

Sure, you just gave me some interesting insights.
