### ISSUE TITLE
[BUG] zero_inflated_regressor.py

### ISSUE THREAD

**Issue by jcoding2022** [koaning/scikit-lego#664]
### The Bug
- The [ZeroInflatedRegressor](https://github.com/koaning/scikit-lego/blob/main/sklego/meta/zero_inflated_regressor.py) class consists of a classifier and a regressor and it says in the documentation that "The regressor is only trained on examples **where the target is non-zero**, which makes it easier for it to focus." In the code, however, the regressor is actually trained on examples **where the classifier-predicted target is non-zero**.

### How to Fix the Bug
- Just replace line 111 with the following code:
```
non_zero_indices = np.where(y != 0)[0]
```

**Comment by FBruzzesi** [comment]
Oh gosh! Thanks for reporting this!
I don't think it was intended, but will double check and get back to you or fix it in the next release 👌
