### ISSUE TITLE
[FEATURE] equivalent to sklearn discovery module

### ISSUE THREAD

**Issue by DCoupry** [koaning/scikit-lego#673]
sklego should have an equivalent to: [sklearn.utils.discovery](https://scikit-learn.org/stable/modules/classes.html#module-sklearn.utils.discovery), a module that stores methods such as:

- all_estimators(filter=typing.Literal["classifier","transformer", etc...])
- all_displays
- all_functions...

This greatly simplifies the automatic use of the library in the context of auto-ML in particular. 
If interested, I can start work on a PR.

**Comment by koaning** [comment]
I am unsure. Looking at the docs it seems that the discovery tools are going away in sklearn. I do not know if something will replace it, but if sklearn is dropping it then I think schikit-lego should not adopt it.

![CleanShot 2024-05-22 at 13 38 54](https://github.com/koaning/scikit-lego/assets/1019791/915f9605-af73-4742-8a00-4d309b18f1af)

**Comment by DCoupry** [comment]
Well dang, it appears this deprecation just came through with 1.5. Do we have a link to the relevant discussion? 
I wonder if it is going back to sklearn.utils.testing as a private function, like it was before / is in imbalanced-learn. 
@FBruzzesi , it could be included in an equivalent to https://github.com/scikit-learn-contrib/imbalanced-learn/blob/master/imblearn/utils/testing.py / https://github.com/scikit-learn/scikit-learn/blob/1.1.X/sklearn/utils/__init__.py instead of in the dicovery module (which apparently will keep on existing with only the all_displays function in it?)

**Comment by FBruzzesi** [comment]
I agree with Vincent, if scikit learn itself is deprecating it and we don't have a relevant use case, it might just be a burden.

I am also debated as arguably:
- it's on the auto-ML library the mandate of _discovering_ features for those libraries that it supports?! 
- there is no standard way of doing such listing, e.g. we have some naive implementation in [feautres.py](https://github.com/koaning/scikit-lego/blob/main/features.py)

**Comment by DCoupry** [comment]
Then let's shelve it until sklearn 1.7 to see what alternative they'll use (the function is quite useful, I doubt they'll remove it entirely unless of course it's too much of a maintenance burden). Or contact them to get an answer directly to future-proof implementation?

**Comment by koaning** [comment]
Shall we close this issue in the meantime?

**Comment by FBruzzesi** [comment]
Closing it as not plan for now. We can come back to it when scikit-learn has something in place
