### ISSUE TITLE
ModuleNotFoundError: No module named 'narwhals' when using RepeatingBasisFunction

### ISSUE THREAD

**Issue by Manohar0077** [koaning/scikit-lego#677]
Hello,

I encountered an issue while trying to use the RepeatingBasisFunction from the sklego.preprocessing module. Here are the details of the error:

  ```
File "/home/ec2-user/anaconda3/envs/testenv/lib/python3.11/site-packages/sklego/preprocessing/__init__.py", line 24, in <module>
    from sklego.preprocessing.pandastransformers import ColumnDropper, ColumnSelector, PandasTypeSelector, TypeSelector
  File "/home/ec2-user/anaconda3/envs/testenv/lib/python3.11/site-packages/sklego/preprocessing/pandastransformers.py", line 5, in <module>
    import narwhals as nw
ModuleNotFoundError: No module named 'narwhals'
```
To reproduce this issue, I used the following installation command:

`conda install conda-forge::scikit-lego`

It appears that the narwhals dependency is not being installed automatically, which leads to the ModuleNotFoundError. According to the documentation, installing scikit-lego should also handle its dependencies.

Could you please look into this issue and ensure that the necessary dependencies are included in the installation process?

Thank you for your assistance.

**Comment by koaning** [comment]
I just updated the conda metadata. The next release should fix this, but for now the manual install may still be required. Sorry about that!

**Comment by Manohar0077** [comment]
Thanks.
