### ISSUE TITLE
[FEATURE] Feature selector by name

### ISSUE THREAD

**Issue by stephanecollot** [koaning/scikit-lego#68]
When you use pandas, you want quickly specify which features to keep and/or which one you want to drop.

Example
```
class FeatureSelector(BaseEstimator):
    def __init__(self, keep=None, drop=None):
        self.keep = keep
        self.drop = drop

    def transform(self, X):
        if self.keep:
            self.feature_names = self.keep
        else:
            self.feature_names = list(set(X.columns) - set(self.drop))
        return X[self.feature_names]

    def fit(self, X, y=None):
        return self
    
    def get_feature_names(self):
        return self.feature_names
```

**Comment by koaning** [comment]
It sounds like this is the same as the feature we have [here](https://github.com/koaning/scikit-lego/blob/master/sklego/preprocessing.py#L56) except that currently we can only select columns and we cannot exclude them. It seems fair to add that to the existing class but I don't think we need a new one.
