### ISSUE TITLE
[DOCS] linear_model missing docstrings

### ISSUE THREAD

**Issue by david26694** [koaning/scikit-lego#689]
Add example in docstring for:
- linear_model.ProbWeightRegression
- linear_model.DeadZoneRegressor
- linear_model.DemographicParityClassifier
- linear_model.EqualOpportunityClassifier

**Comment by david26694** [comment]
started work in https://github.com/koaning/scikit-lego/pull/690

**Comment by FBruzzesi** [comment]
Hey @david26694 , thanks for the issue and already starting to work for fix these docstrings.
I am closing this in favour (as duplicate) of #596 - let's keep the discussion for docstrings there :)
