### ISSUE TITLE
[FEATURE] Enable GroupedTransformer to work with .set_output(transform="pandas")

### ISSUE THREAD

**Issue by olivier-s-j** [koaning/scikit-lego#696]
In Scikit-learn the `set_output` API was recently introduced: https://scikit-learn.org/stable/auto_examples/miscellaneous/plot_set_output.html

However, unless I am mistaken, Scikit-lego is not yet compatible with this. It would be nice to have this compatibility.

I came across this incompatibility when creating:

```python
ColumnTransformer(
            transformers=[
                (
                    "cat",
                    OrdinalEncoder(
                        handle_unknown="use_encoded_value", unknown_value=-1
                    ),
                    categorical_features,
                ),
                (
                    "cont",
                    GroupedTransformer(
                        StandardScaler(), groups=["GROEP_A", "GROEP_B"]
                    ),
                    continuous_features
                ),
            ],
            verbose_feature_names_out=False,
        ).set_output(transform="pandas")

```

Which results in:

```
ValueError: Unable to configure output for GroupedTransformer(groups=['GROEP_A', 'GROEP_B'],
                   transformer=StandardScaler()) because `set_output` is not available.
```

**Comment by FBruzzesi** [comment]
Hey there! Thanks for reporting this issue. This should certainly be possible and it should be enough to implement `get_feature_names_out` (as explained in the [official doc section](https://scikit-learn.org/stable/developers/develop.html#developer-api-for-set-output)). 

@olivier-s-j please let us know if you would be interested in opening a PR tackling `GroupedTransformer`.

@koaning this could be a nice addition and a quick win for most transformers honestly.
