### ISSUE TITLE
[FEATURE]  Time Series Split with gap and column parameter

### ISSUE THREAD

**Issue by stephanecollot** [koaning/scikit-lego#70]
Time Series Split with a gap parameter between train and testing

Between the blue and the red we want to have a gap, to simulate that in production you need to wait x days before creating your target that looks x days ahead (e.g. case when you want to predict value in x days).
![image](https://user-images.githubusercontent.com/1184396/54839664-aa417780-4ccb-11e9-9d85-cb11f48d523a.png)

Also sometime you have multiple sample per days, the current scikit learn implement doesn't support specifying a date column.

**Comment by koaning** [comment]
I wonder. Is this something that is fixed on a label level or is this something that is fixed on a cross validation level.

**Comment by stephanecollot** [comment]
Nop this cannot be solved with modification of the label. The gap is a simulation of the fact that in production you are dropping the last forward looking window available.

**Comment by MBrouns** [comment]
this was merged in #97
