### ISSUE TITLE
[DOCS] debug pipeline has rendering issues

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-lego#74]
![image](https://user-images.githubusercontent.com/1019791/54864157-42367400-4d53-11e9-9ca4-30532b5f78ee.png)

**Comment by koaning** [comment]
This is also confirmed by running:

```
 python -m doctest sklego/pipeline.py 
```

It **might** be possible that I merged a tad bit early there. @MBrouns @CorXccelerated

**Comment by CorXccelerated** [comment]
Solved in the merge request #78
