### ISSUE TITLE
[FEATURE] add log_dtypes to pandas_utils

### ISSUE THREAD

**Issue by koaning** [koaning/scikit-lego#99]
I might also want to log the `dtypes` between each step in a pandas pipeline. It's probably best to add a separate logger for both the `dtype` as well as the shape. 

Should the column names be seperate too? Maybe worth a discussion. 

It would also be nice if these features were documented on the documentation page together with some other `pandas_utils` functions.

**Comment by koaning** [comment]
After thinking about it, we probably want to have these three:

- log_shape
- log_names
- log_dtypes 

Note too sure about `log_names` and `log_dtypes`.

**Comment by david26694** [comment]
Is this still open? I'd be happy to take it

**Comment by koaning** [comment]
It is still open, but let's first make sure we're clear on what will get implemented. Do you want to implement `log_dtypes` or also `log_names`? 

Relevant: there's a related issue too https://github.com/koaning/scikit-lego/issues/371.

**Comment by david26694** [comment]
I was thinking about both. I don't fully understand what is happening in #371, why is matplotlib generating warnings and what would the print step do?

**Comment by koaning** [comment]
The print step would do a very similar thing to what `log_step` would do but it would use `print` instead of using the python logging framework. The reason why matplotlib is generating warnings is because we've configured a logger to work in the notebook. This allows you to receive logs from `log_step` (this is awesome for production) but you might also get the logs from other libraries (which is not awesome in a notebook).

**Comment by koaning** [comment]
This got adressed.
